### ISSUE TITLE
Want to pick images from a specific folder

### ISSUE THREAD

**Issue by youssef007** [esafirm/android-image-picker#101]
Hello,
I want to use your lib to pick images from a specific folder for example : "/storage/emulated/0/My folder". I changed this in your sample code : 
`imagePicker.limit(10)
                .showCamera(false)
                .imageFullDirectory(Environment.getExternalStorageDirectory().getPath()+"/My folder")
                .start();`
But it still showing all images.

**Comment by esafirm** [comment]
`imageFullDirectory` specify the camera save location. Currently you can't pick image from specific directory.

**Comment by esafirm** [comment]
Closing due to duplication https://github.com/esafirm/android-image-picker/issues/67
