### ISSUE TITLE
[Feature] Return after first from camera, but multi otherwise

### ISSUE THREAD

**Issue by sebastian-raubach** [esafirm/android-image-picker#102]
Thanks for developing this amazing library. It's a pleasure to use so far and has saved me a considerable amount of time.

While testing our app with some users they highlighted that the following use-case was a bit frustrating:

1. Open image picker
2. Decide to take a new photo and click on the appropriate icon
3. Take the photo
4. Search for the folder representing the photos taken by the camera ("Camera" by default)
5. Select the image just taken with the camera

They all thought, that it should work like this:
1. Open image picker
2. Decide to take a new photo and click on the appropriate icon
3. Take the photo
4. Automatically return to the calling app

I assume that is possible if you use `returnAfterFirst(true)`, but that forces me to use `single()` as well.
I do very much like the option to select multiple pre-existing images as well.

So ideally, it would be nice if this library supported the following: Select multiple pre-existing images, but return straight after a new photo has been taken using the camera.

**Comment by esafirm** [comment]
Hi @sebastian-raubach, you're welcome. 

Actually this adjustment you talking about is already made in here 
https://github.com/esafirm/android-image-picker/commit/266c88bfbb475eb0828a8e0d9259883fbd164dcf

But i haven't had a time to create a release and make a documentation for it. Also i haven't had a time to do more testing (it would be great if we have an Espresso test case for this kind of thing)  

Will update it tonight ✔️

**Comment by sebastian-raubach** [comment]
Sounds great 👍 
So that will allow me to both instantly return after camera and also to pick multiples from picker with the same call?

**Comment by esafirm** [comment]
Yep, you need `ReturnMode.CAMERA_ONLY` for that. 
It basically translate to `setReturnAfterFirst but for camera only` 

Do you have a better name for it? 😄

**Comment by sebastian-raubach** [comment]
So does the `ReturnMode` decide for which operation (camera, gallery, all, none) it should return instantly?

**Comment by esafirm** [comment]
Yes. it also make `setReturnAfterFirst` obsolete.

**Comment by esafirm** [comment]
Released https://github.com/esafirm/android-image-picker/releases/tag/1.12.0 🎉
