### ISSUE TITLE
[Feature] Option to sort images and folders

### ISSUE THREAD

**Issue by sebastian-raubach** [esafirm/android-image-picker#103]
It would be great if the library allowed sorting of the folders and images.
As a first instance, ascending and descending based on name would be great, but ideally the option to specify a `Comparator<File>` would be the best option.

**Comment by esafirm** [comment]
@sebastian-raubach CMIIW this feature is to sort the image programatically only right? There's is no UI to sort it on the image picker itself? 

My concern with more and more features like this is that it requires to be passed to the `Intent` via `Parcelable` or `Serializeable`. I don't know if it's going to break somehow or it is just me getting anxious 😈

**Comment by sebastian-raubach** [comment]
Either would be great, actually. So programmatically pre-defining the sort order based on a comparator or letting the user sort things on the UI would both work for me, as long as it remembers the sort order that the user selected for the next run.

**Comment by tianzhuqiao** [comment]
Is there any plan to support this feature? It will be very useful if a device has a lot of pictures and folders. Thanks

**Comment by esafirm** [comment]
This is currently supported with custom image file loader
https://github.com/esafirm/android-image-picker/blob/master/docs/custom_components.md
