### ISSUE TITLE
Taken pictures are wrong rotated

### ISSUE THREAD

**Issue by antoniovlasic** [esafirm/android-image-picker#104]
Sometimes the pictures I take fron the camera icon are wrong rotated. ExifInterface?

**Comment by esafirm** [comment]
@antoniovlasic is it inside the picker or after you receive the result?

**Comment by antoniovlasic** [comment]
It's already saved wrong. I'm only checking for the path.

**Comment by esafirm** [comment]
> It's already saved wrong. I'm only checking for the path.
Sorry i still don't get it. Can you give me some example? 

Anyway, image saving is not image picker responsibility, it's the camera app used by the image picker responsibility.

Image rotation *inside* the image picker should be handled by the `ImageLoader` which is defaulted to `Glide`. And it should handle the rotation properly.

If you want to have a right rotation after you receive the result from image picker, then i guess you have to handle the rotation yourself when you want to show it up.

**Comment by Tsepaka** [comment]
@esafirm Hello, I have this issue reproduced as well. Please see these two photos taken on Pixel 2 device in portrait mode. One of them was taken trough built-in camera app, second - from within a gallery. As you can see, Exif data differs there.
First photo Exif: 
ImageWidth : 3024
ImageHeight : 4032
Orientation : 1
Second photo Exif:
ImageWidth : 4032
ImageHeight : 3024
Orientation : 6


![camera photo](https://user-images.githubusercontent.com/1786143/41028595-74703114-6982-11e8-9c6e-0060264e8fa3.jpg)

![library photo](https://user-images.githubusercontent.com/1786143/41028609-7b1c9462-6982-11e8-8f23-c909d5fbe78d.jpg)

**Comment by tyshcr** [comment]
Has anyone found a solution to this? 

We are having the problem, using Image Picker 1.13.1
