### ISSUE TITLE
I am using 1.8.0 but i dont need glide is it possible with this library

### ISSUE THREAD

**Issue by amankumarjain** [esafirm/android-image-picker#105]
I am using fresco for image loading, and with this library glide gets added in my external libraries how to remove it?

in your dependencies:
final glideVersion = '4.5.0'
implementation "com.github.bumptech.glide:glide:$glideVersion"

is it possible to use it without glide?

**Comment by esafirm** [comment]
@amankumarjain i think if you set a custom `ImageLoader` and then exclude Glide in the `build.gradle`

But i haven't tried it yet.

**Comment by amankumarjain** [comment]
ok i will try that, just want to know if glide is being used in this library or not? otherwise it will break something else.

**Comment by sebastian-raubach** [comment]
@amankumarjain If you try this and get it working, please let me know. I'm already using Picasso and would prefer not to include Glide as well if it's not necessary.

**Comment by Galaxer** [comment]
This library does use Glide. Excluding Glide via Gradle will cause a crash when starting the picker activity because it can't find Glide. Example of the Gradle dependency entry I tried (tested with 1.12.0):

```
api(libs.imagePicker, {
    exclude group: 'com.github.bumptech.glide', module: 'glide'
})
```

**Comment by esafirm** [comment]
Thanks @Galaxer for confirming this. I think i should add this somewhere 😄

**Comment by esafirm** [comment]
Included in README. Closing this. Thanks all 🙏

**Comment by AdityaAnand1** [comment]
Great job @Galaxer!

@esafirm Perhaps this should be incorporated within the library somehow? 

* Either include the above snippet directly
* Provide a base library dependency along with multiple optional sub-dependencies hooking up image picker with the user's choice of library?

**Comment by AssemMahrous** [comment]
@amankumarjain how did you managed to add fresco as a custom image Loader

**Comment by djdance** [comment]
Java example for Picasso

`import android.widget.ImageView;
import com.esafirm.imagepicker.features.imageloader.ImageLoader;
import com.esafirm.imagepicker.features.imageloader.ImageType;
import com.squareup.picasso.Picasso;

public class PicassoImageLoader implements ImageLoader {

  @Override
  public void loadImage(String path, ImageView imageView, ImageType imageType) {
    Picasso.get()
            .load("file://"+path)
            .resize(500, 500).centerCrop()
            .into(imageView);
  }
}
`

**Comment by AssemMahrous** [comment]
I have managed to add Fresco like this

`import android.content.res.Resources;
import android.graphics.drawable.Drawable;
import android.net.Uri;
import android.widget.ImageView;

import com.esafirm.imagepicker.features.imageloader.ImageLoader;
import com.esafirm.imagepicker.features.imageloader.ImageType;
import com.facebook.common.util.UriUtil;
import com.facebook.drawee.backends.pipeline.Fresco;
import com.facebook.drawee.drawable.ProgressBarDrawable;
import com.facebook.drawee.generic.GenericDraweeHierarchy;
import com.facebook.drawee.generic.GenericDraweeHierarchyBuilder;
import com.facebook.drawee.interfaces.DraweeController;
import com.facebook.drawee.view.DraweeHolder;
import com.facebook.imagepipeline.common.ResizeOptions;
import com.facebook.imagepipeline.request.ImageRequest;
import com.facebook.imagepipeline.request.ImageRequestBuilder;

public class FrescoImageLoader implements ImageLoader {


    @Override
    public void loadImage(String path, ImageView imageView, ImageType imageType) {
        Drawable defaultDrawable = imageView.getDrawable();
        Resources resources = imageView.getContext().getResources();
        GenericDraweeHierarchy hierarchy = new GenericDraweeHierarchyBuilder(resources)
                .build();
        final DraweeHolder<GenericDraweeHierarchy> draweeHolder = DraweeHolder.create(hierarchy, imageView.getContext());
        draweeHolder.getHierarchy().setProgressBarImage(new ProgressBarDrawable());
        Drawable drawable = draweeHolder.getHierarchy().getTopLevelDrawable();
        if (drawable == null) {
            imageView.setImageDrawable(defaultDrawable);
        } else {
            imageView.setImageDrawable(drawable);
        }

        Uri uri = new Uri.Builder()
                .scheme(UriUtil.LOCAL_FILE_SCHEME)
                .path(path)
                .build();
        ImageRequest imageRequest = ImageRequestBuilder
                .newBuilderWithSource(uri)
                .setResizeOptions(new ResizeOptions(200, 200))
                .build();
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setOldController(draweeHolder.getController())
                .setImageRequest(imageRequest)
                .build();
        draweeHolder.setController(controller);

    }
}`

**Comment by Elias8** [comment]
I use it with picasso like this 

Image image = ImagePicker.getFirstImageOrNull();

Picasso.get()
             .load("file://".concat(image.getPath()))
           .resize(100, 100)
           .centerCrop()
           .into(imageView);

but I am not sure this is the best way.

**Comment by logan2222** [comment]
Hi All! I have a question!
It is possible to allow only images in landscape?
