### ISSUE TITLE
Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found

### ISSUE THREAD

**Issue by jinfagang** [esafirm/android-image-picker#107]
Hi, thanks for this very good library, really saved my life when app needs picking multiple images. However, currently I get a only one problem which specific on Xiaomi android devices:

```
Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found
```

Totally have no idea why this error happen, and other device just ok. I know it's Xiaomi's problem, but I am in China and this device are so many, how to solve this anyway?

**Comment by esafirm** [comment]
Does the app crash or something? 
When exactly this error happen? 
Can you attach the full stack trace?

**Comment by jinfagang** [comment]
@esafirm Hi, no crash, seem the exception were be catched. The only trace back can be seem from logcat. Just `Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found`. And can not open image pickcer. This error only shows on Xiaomi devices.

**Comment by esafirm** [comment]
It seems like the issue is not from the image picker itself. On [this](https://github.com/BlinkID/blinkid-android/issues/42) it mentioned the issue is from the audio processor or something. 

I have Xiaomi Note 4 myself, unfortunately the issue didn't reproducible as well.

**Comment by jinfagang** [comment]
Hi, esa, thanks for replying the related issue, I am using Redmi 5 Plus. If you find solution about this pls let me know!

**Comment by esafirm** [comment]
@jinfagang will do! As for now, i will closing this issue. Please don't hesitate to reopen.

**Comment by unicornRainbows** [comment]
FML

**Comment by cloewen8** [comment]
Just had this issue with Android Nexus 6 (API 25) virtual device.

**Comment by shekharartemedia** [comment]
Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found. i am getting this issue  on lava phone when i open the gallery from my app.

**Comment by Rameez-Rahil** [comment]
Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found.in my emmulator pixel 2XL device

**Comment by EmreOzkose** [comment]
E/WVMExtractor: Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found in my virtual device : Nexus 5 API 24
