### ISSUE TITLE
can i capture more than one images at a time from camera? 

### ISSUE THREAD

**Issue by BhargavVGhodasara** [esafirm/android-image-picker#108]
i want to add more than 1 imges from camera at a time.

**Comment by esafirm** [comment]
@BhargavVGhodasara you can capture more than 1 image in multiple mode. But the flow would be 
Camera -> Picker -> Camera -> Picker -> Your Screen
Not 
Camera (2x) -> Picker -> Your Screen

This is because we do not use a custom camera code.

**Comment by BhargavVGhodasara** [comment]
thank you @esafirm

**Comment by yasserakbbach** [comment]
@esafirm I **don't** get it!
