### ISSUE TITLE
NPE in ImagePickerActivity sample

### ISSUE THREAD

**Issue by chpasha** [esafirm/android-image-picker#110]
onCreate() -> setupComponents() -> getImageSource() -> config.getImageSource() - config is not initialized yet => NPE. To fix this, use getImagePickerConfig().getImageSource() instead

**Comment by esafirm** [comment]
I'm not sure we have `getImageSource()` method somewhere in the code. Could you please point it by a link?

Anyway, i will refactor anything that refer to `config` directly and use `getImagePickerConfig()` instead.

**Comment by chpasha** [comment]
you are right, I must have made some mistake merging master with my version, so I've got some mix of old and new code

**Comment by esafirm** [comment]
Ah no prob 👍
