### ISSUE TITLE
Failed to create image file

### ISSUE THREAD

**Issue by mamini** [esafirm/android-image-picker#111]
In Android >=6 I receive "Failed to create image file" when using camera only. permission prompt for camera is shown but for writing to external storage no prompt shown.

Could you help me?

**Comment by Shikou** [comment]
You need to request manually the WRITE_EXTERNAL_STORAGE permission

**Comment by esafirm** [comment]
Resolved by https://github.com/esafirm/android-image-picker/commit/2b79e45d60568f02b4a6c9bbd70c650fe8b8449b
