### ISSUE TITLE
App Crashed

### ISSUE THREAD

**Issue by andazlan** [esafirm/android-image-picker#113]
`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.isEmpty()' on a null object reference
                                                       at com.esafirm.imagepicker.features.ImagePickerActivity.setupExtras(ImagePickerActivity.java:134)
                                                       at com.esafirm.imagepicker.features.ImagePickerActivity.onCreate(ImagePickerActivity.java:100)`

App crashed when i use ImagePicker.MODE_MULTIPLE.

FYI, i use traditional intent like :
`Intent intent = new Intent(this, ImagePickerActivity.class);
        intent.putExtra(ImagePicker.EXTRA_FOLDER_MODE, true);
        intent.putExtra(ImagePicker.EXTRA_MODE, ImagePicker.MODE_MULTIPLE);
        intent.putExtra(ImagePicker.EXTRA_LIMIT, 10);
        intent.putExtra(ImagePicker.EXTRA_SHOW_CAMERA, true);
        intent.putExtra(ImagePicker.EXTRA_FOLDER_TITLE, "Album");
        intent.putExtra(ImagePicker.EXTRA_IMAGE_TITLE, "Tap to select images");
        intent.putExtra(ImagePicker.EXTRA_IMAGE_DIRECTORY, "Camera");
        intent.putExtra(ImagePicker.EXTRA_RETURN_AFTER_FIRST, true); //default is false
        startActivityForResult(intent, REQUEST_PHOTO_PICKER);`

**Comment by esafirm** [comment]
Traditional intent is not supported anymore. Sorry :(

**Comment by andazlan** [comment]
awh so sad, thank you :)
