### ISSUE TITLE
Camera folder showing empty images

### ISSUE THREAD

**Issue by MogiLogi** [esafirm/android-image-picker#116]
**Hello , thank you for your lib it's great 
i'm having a problem when i chose camera to take a picture , then i don't like it and cancel it and close camera , then try to choose image from my list normally , camera folder start to show a empty pictures 
seems like when i take  a picture by camera a field is being added in case i accept the picture but when i reject the picture , this field stays , and even i restart the app the empty picture still showing , even there is no files in my Camera folder** 

<a href="https://ibb.co/cKsMV7"><img src="https://preview.ibb.co/bQsc3S/bug.jpg" alt="bug" border="0"></a>

thank you.

**Comment by esafirm** [comment]
Hi, thank you!

For your problem, could you please tell me your:

1. OS and Phone
2. Camera App that used for your image taking
3. Your Image Picker configuration

Cheers!

**Comment by esafirm** [comment]
Should be resolved by https://github.com/esafirm/android-image-picker/commit/2b79e45d60568f02b4a6c9bbd70c650fe8b8449b
