### ISSUE TITLE
Suggestion: single selection -> immediately return without need of "DONE" toolbar-btn

### ISSUE THREAD

**Issue by Rainer-Lang** [esafirm/android-image-picker#12]

**Comment by esafirm** [comment]
You can use 
```
ImagePicker.create(this)
    .returnAfterCapture(true)
```

**Comment by Rainer-Lang** [comment]
I'm using Intent (with RxActivityResult: https://github.com/VictorAlbertos/RxActivityResult ).

**Comment by Rainer-Lang** [comment]
I have to press DONE - and I'm not able to set returnAfterCapture wit usage of intent.

**Comment by esafirm** [comment]
@Rainer-Lang currently this can't be done through intent. Will update soon

**Comment by Rainer-Lang** [comment]
@esafirm Thanks a lot.

**Comment by esafirm** [comment]
Hello @Rainer-Lang 

On the version `1.3.0` you can now using `returnAfterFirst` to make a selection of image without pressing `Done`.

Please notice for picking action, you must use `SINGLE_MODE` to make it works.

Thanks

**Comment by Rainer-Lang** [comment]
@esafirm Just wanted to thank you. It's working perfect! 👍

**Comment by mdumrauf** [comment]
@esafirm is this broken? I didn't want to open a new issue. I am using the latest 1.7.3 and starting the picker with:

```java
ImagePicker.create(SomeFragment.this)
                .returnAfterFirst(true)
                .single()
                .imageTitle("Tap en la imagen")
                .showCamera(true)
                .imageDirectory("Camara")
                .start(REQUEST_CODE_PICKER);
```

The picker starts, it doesn't display the "DONE" button and enables single select mode. However, it is not returning after first tap. It is working for camera though.

**Comment by esafirm** [comment]
@mdumrauf Investigating. It's ok if you want to create new issue. I thinks it's more trackable.
