### ISSUE TITLE
Will there be a release for video selection anytime soon?

### ISSUE THREAD

**Issue by idish** [esafirm/android-image-picker#128]
Hello, 
I saw that the library added video support about 2 months ago, 
are there any expectations to the date that it will be released to public use?

Cheers !

**Comment by esafirm** [comment]
Hi sorry for the inconvenience 🙏will update this ASAP

**Comment by esafirm** [comment]
Released. Changelog is on its way! 
https://github.com/esafirm/android-image-picker/releases/tag/1.13.0

**Comment by nicholashartono** [comment]
Hi, I still waiting for the video support update, any news about this update?

Thx

**Comment by esafirm** [comment]
@nicholashartono video selection support is already release on `1.13.0` haven't got a chance to update the changelog and release note though .. 🙈
