### ISSUE TITLE
Using native image explorer

### ISSUE THREAD

**Issue by aimanbaharum** [esafirm/android-image-picker#13]
Is there a way we can use the native image explorer instead of ImagePickerActivity?

**Comment by esafirm** [comment]
@aimanbaharum I'm not sure what you mean by "Native Image Explorer". Can you please elaborate more on this?

**Comment by aimanbaharum** [comment]
Instead of using ImagePickerActivity which is using a custom file explorer, we use the native Android file explorer one. The one with 3rd party apps at the navigation drawer (eg. Dropbox, Quickpic, Photos etc)?

**Comment by esafirm** [comment]
Sorry, our goal is to providing an "as simple as possible" drop-in replacement for 3rd party image picker. 

So yeah, this is not our focus right now.

**Comment by aimanbaharum** [comment]
But is it true that it is a hassle dealing with images coming from the native explorer ones? I never used custom explorer, but as far as I can tell, dealing with path URI is quite a pain when it comes to permission and stuff.
