### ISSUE TITLE
Image picker takes too long to load

### ISSUE THREAD

**Issue by idish** [esafirm/android-image-picker#133]
Hello,
It's great to have this library, thank you! 😊 

I think that one of the top priorities of libraries like these are that they will be fast.
It seems that opening the gallery and viewing the contents just takes too much time, and it would be great if we could reduce this time to minimum. Currently it takes about **11 seconds** till the loading bar disappears and it starts showing my gallery folders.

Here's the android profiler result:
<img width="1646" alt="screen shot 2018-05-18 at 16 45 44" src="https://user-images.githubusercontent.com/5266462/40238144-06b9e8ac-5abb-11e8-90b9-72002e66db2d.png">

So it seems that `run` method, which actually loads everything takes too long. 
Does it really have to take 11 seconds to run the cursor?

From the profiler result we can see that the **`exists` method takes 8.6 seconds (!!!!)**  Which is like 5/6 of the time that it takes to load everything.
I guess it is because of IO blocking operations.
We must find a solution for that. so the library will load our contents much more faster.

**Comment by Midhilaj** [comment]
in my phone it take 30s for load

**Comment by esafirm** [comment]
Should be fixed in https://github.com/esafirm/android-image-picker/releases/tag/1.13.1
