### ISSUE TITLE
Suggestion to folder loading

### ISSUE THREAD

**Issue by Rodrigolmti** [esafirm/android-image-picker#136]
Hello, first thank you so mutch for doing that lib and share with us, for me is the best lib to pick images, but I found one problem with the folder loading, if your device have many images the loading will be a great delay, because at first you search for the folder and then you put all images of that folder inside, but why not load only the folders, and when user select one folder, then you load images from that folder, i download your code and made some modifications and it works, what do you think about that? Maybe can i sent to you the modifications i made.

**Comment by esafirm** [comment]
Yeah, load images per-folder is a more scalable approach for sure. Currently there's an issue for loading speed as reported in [here](https://github.com/esafirm/android-image-picker/pull/142).

**Comment by esafirm** [comment]
Hey @Rodrigolmti can you check the latest release for your delay problem? https://github.com/esafirm/android-image-picker/releases/tag/1.13.1

**Comment by Rodrigolmti** [comment]
Hey sorry for the delay, I actually edit myself the code haha. But I see here and It's working now, thanks for that.
