### ISSUE TITLE
onActivityResult in Fragments not called in version 1.3.0

### ISSUE THREAD

**Issue by vananit** [esafirm/android-image-picker#14]
But onActivityResult is called in version 1.2.5.
Sorry by my english is bad :(.
Thanks for your libs :+1:

**Comment by esafirm** [comment]
@vananit will check it ASAP

**Comment by esafirm** [comment]
@vananit did you call `super.onActivityResult` on the host `Activity`? 

I added `Fragment` to the sample and there is no issue.

Please look at this http://stackoverflow.com/questions/6147884/onactivityresult-is-not-being-called-in-fragment

**Comment by esafirm** [comment]
Will closing this for now.
