### ISSUE TITLE
Warning when add lib in dependencies.

### ISSUE THREAD

**Issue by Zimzik** [esafirm/android-image-picker#146]
When I add this lib v 1.13.0 to dependencies, i get this warning: 
![warning](https://user-images.githubusercontent.com/22100515/41434120-68105154-7023-11e8-87bd-0126a999203d.jpg)

**Comment by esafirm** [comment]
You should resolve the dependency in your app gradle. Some ref: https://medium.com/mindorks/avoiding-conflicts-in-android-gradle-dependencies-28e4200ca235

**Comment by esafirm** [comment]
Support library now updated to 27.1.1
If you have another conflict of dependency you can always use resolution strategy or excluding app compat from the library. 

Closing this.
