### ISSUE TITLE
How to change image save location while image is captured using camera.

### ISSUE THREAD

**Issue by kaprat** [esafirm/android-image-picker#150]
I want to save in **/storage/emulated/0/MY_FOLDER** but .imageDirectory("MY_FOLDER") saves image in **/storage/emulated/0/Pictures/MY_FOLDER**

Also image is captured with improper rotation (ExifInterface)

**Comment by esafirm** [comment]
`imageDirectory` will only change the folder name, not the full path. 
To change save location, please use `setImageFullDirectory`
