### ISSUE TITLE
can i select only videos and only images using this API

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [esafirm/android-image-picker#151]
can i select only videos or only images using this API ?
if yes, what the option to set for selecting only images and for selecting only videos ?
if no, can you please add this feature.

**Comment by esafirm** [comment]
Sorry for the late response. Yes you can! 

Please check [this](https://github.com/esafirm/android-image-picker/releases/tag/1.12.0) and the sample app!

**Comment by cyberpwnn** [comment]
Could this be implemented?

**Comment by malwinder-s** [comment]
@esafirm  Can you please implement library functionality to support picking of only videos?

**Comment by HiteshDevganiya** [comment]
@esafirm includeVideo(false) not working. `DefaultImageFileLoader`
if (onlyVideo) {
// only video
} else if (includeVideo) {
// image or video 
} else {
// images only
}

**Comment by esafirm** [comment]
You can use `onlyVideo(boolean)` for this use case.
