### ISSUE TITLE
Make a Fragment version of the ImagePicker

### ISSUE THREAD

**Issue by Ruberik** [esafirm/android-image-picker#156]
I'm planning to do this, and I'd like to get feedback and advice about it.

I'd like to use the ImagePicker as one part of a larger Activity. One part of the Activity would be the ImagePicker, and another part would be a preview of the most recently selected image.

To make this possible, I want to move most of ImagePickerActivity's logic into a new class called ImagePickerFragment. Developers like me could create their own Activity class to take the place of ImagePickerActivity.

Please let me know what you think.

**Comment by esafirm** [comment]
@Ruberik well actually i'm planning on moving the the picker to views. WDYT?

**Comment by Ruberik** [comment]
I haven't done a lot of Androids programming, so please take my opinion only for what it's worth.

I like that Fragments have their own lifecycle management. For example, in a Fragment you could retain what's been selected, what Album was open, and where the user has scrolled to. That's possible to do with a View, but requires work from the developer.

To me, broadly, a Fragment is a good place to put something interactive. A View is where you put something to look at. Android Image Picker is heavily interactive, with lots of state, so I'd use a Fragment.

That said, I don't have a lot of Android experience, and I'm not the primary maintainer of this library, so my opinion is only useful inasmuch as it informs yours. :-)

**Comment by Ruberik** [comment]
@esafirm, following up: What do you think is the best approach here? Do you prefer Fragments or Views, and should I be working on it, or would you prefer to?

**Comment by Ruberik** [comment]
See #164.

**Comment by Ruberik** [comment]
Fixed in #166.
