### ISSUE TITLE
Data's not update

### ISSUE THREAD

**Issue by ulaslaslas** [esafirm/android-image-picker#16]
Hi.
First I picked two pictures. With ImageRx button.
When I approve it, it prints the path to these pictures on the screen.
Then I did just the same thing and selected just one image.
This time the data is updated and the old data remains on the screen.

![untitled](https://cloud.githubusercontent.com/assets/12948351/21610533/2dd4eb22-d1d1-11e6-8ab3-24b579d70f00.png)

@esafirm

**Comment by esafirm** [comment]
Fixed in `1.3.1` 😊

**Comment by ulaslaslas** [comment]
But rximagepicker version is still 1.3.0
