### ISSUE TITLE
Gallery shows deleted files

### ISSUE THREAD

**Issue by deputat007** [esafirm/android-image-picker#171]
Please check in ImageFileLoader if file exists
` if (file != null && file.exists()) {
            if (exlucedImages != null && exlucedImages.contains(file)) {
              continue;
            }`

**Comment by esafirm** [comment]
Hmm interesting, have you tried triggering the media scanner after you delete the file?

**Comment by deputat007** [comment]
> Hmm interesting, have you tried triggering the media scanner after you delete the file?

No, I just removed photo in gallery and noticed that it is still visible in ImagePickerActivity. 

> Please check in ImageFileLoader if file exists
> `if (file != null && file.exists()) { if (exlucedImages != null && exlucedImages.contains(file)) { continue; }`
This will help to fix this bug.

**Comment by idish** [comment]
Just a side note: Checking for each file if it exists via `file.exists`, makes the loading much more slow.
See my accepted PR: https://github.com/esafirm/android-image-picker/pull/142

**Comment by noman720** [comment]
I'm facing the same problem. In my case, I have to move the captured/gallery image to the apps external directory. After moving some selected images to apps external directory, the ImagePicker shows those images again in the gallery which does not exist.

**Comment by sranjith096** [comment]
@esafirm @deputat007 I experienced this issue and got to know that the entry in `MediaStore` wasn't removed and that is the reason it was still shown in the `ImagePicker`, and also the deleted file was shown in Google Photos app as well. I noticed this case when I deleted the file programmatically (didn't notify `MediaStore`), but the files which were deleted using Google Photos app or the Google Files app **(which implicitly notifies MediaStore)** didn't show up in ImagePicker which is the expected scenario.

**Comment by esafirm** [comment]
Related to https://github.com/esafirm/android-image-picker/issues/309
Fixed in https://github.com/esafirm/android-image-picker/pull/370
