### ISSUE TITLE
Customize title style and camera icon color

### ISSUE THREAD

**Issue by ghost** [esafirm/android-image-picker#175]
I'd like the text size and color of the toolbar. Additionally I'd like to be able to tint the camera icon. Is this already possible, did I overlook something?

**Comment by jayearn** [comment]
OK, just saw the PR https://github.com/esafirm/android-image-picker/pull/155
So, at least I'm not the only one who wants that. I'd be also totally fine if a library user would be able to just put an own file with the same name like `ef_ic_camera_white` in the using app-project.

**Comment by djohannot** [comment]
Could it be also possible to change the view `view_alpha` to change the color of the background? If we set a custom color that we get from the colors.xml, then any user can overwrite it :) Cause in the case you have many picture with white background, the alpha over it is useless..

**Comment by esafirm** [comment]
Duplicate of https://github.com/esafirm/android-image-picker/issues/144
