### ISSUE TITLE
cannot resolve includeVideo(true)

### ISSUE THREAD

**Issue by alexandrpersin** [esafirm/android-image-picker#185]
Hi all,

I am using  com.github.esafirm.android-image-picker:imagepicker:**1.12.0** version, and when I add includeVideo() to builder I get an error "Cannot resolve method" 

Kind regards,
Alexandr

**Comment by esafirm** [comment]
It should be there

https://github.com/esafirm/android-image-picker/blob/master/imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePicker.java#L161

Anyway, you should use the new version
