### ISSUE TITLE
Cancelled camera shots leave 0B artifacts

### ISSUE THREAD

**Issue by rustycamper** [esafirm/android-image-picker#188]
When user takes a pic using the camera and then cancels (X outs) the image, an empty 0 byte file is left on the file system.

**Comment by esafirm** [comment]
Yeah, but sometimes i can't reproduce it. Do you think this is the camera app bug? 
I'm very happy to review the PR for this

**Comment by kroegerama** [comment]
Until @esafirm accepts this pull request and creates a new release, everyone can use:
`implementation 'com.kroegerama:android-image-picker:4583344'`
So the device will not get filled up with empty files.

**Comment by esafirm** [comment]
Hi sorry been busy for the past few months. The fix is already merged. Cheers!
