### ISSUE TITLE
Failed to create image file in api 17

### ISSUE THREAD

**Issue by hamidrezakhajeh** [esafirm/android-image-picker#191]
When we click on the button to select a photo through the camera, we will encounter this error:
"Failed to create image file"
API 17

**Comment by shaon2016** [comment]
I have faced this problem also. I think this library doesn't invoke permissions automatically when we use cameraOnly option. So you need to invoke permissions by yourself. 

`Dexter.withActivity(this).withPermissions(
                            arrayListOf(Manifest.permission.CAMERA,
                                    Manifest.permission.READ_EXTERNAL_STORAGE,
                                    Manifest.permission.WRITE_EXTERNAL_STORAGE))
                            .withListener(object : MultiplePermissionsListener {
                                override fun onPermissionsChecked(report: MultiplePermissionsReport?) {
                                    ImagePicker.cameraOnly().start(this@JobAdPostFormActivity, REQUEST_IMAGE_CAPTURE)

                                }

                                override fun onPermissionRationaleShouldBeShown(permissions: MutableList<PermissionRequest>?, token: PermissionToken?) {
                                    token?.continuePermissionRequest()
                                }
                            }).check()`

**Comment by esafirm** [comment]
Should be fixed in 3.0.0
