### ISSUE TITLE
how to get uri from images (getPath() return null when upload to server)

### ISSUE THREAD

**Issue by tranquoctrungcntt** [esafirm/android-image-picker#198]
how to get uri from images (getPath() return null when upload to server)

**Comment by esafirm** [comment]
What do you mean "when upload to server"?

**Comment by tranquoctrungcntt** [comment]
when i Log.d these Uri, it file, but when putFile with Firebase it crash and say null. I will try again and tell you the detail.

**Comment by grabcityinfo** [comment]
> What do you mean "when upload to server"?

He want to get the Uri of image capture from Camera or Gallery

**Comment by rupert2133** [comment]
same issue here.. im getting null when selecting image

Uri img = data.getData();

**Comment by esafirm** [comment]
> Uri img = data.getData();

AFAIK this is deprecated and we internally don't use it as well. 

Closing this issue
