### ISSUE TITLE
INTENT_EXTRA_SELECTED_IMAGES missing [Update Readme]

### ISSUE THREAD

**Issue by ysoftware** [esafirm/android-image-picker#20]
Your Readme file says, I should use ImagePickerActivity.INTENT_EXTRA_SELECTED_IMAGES constant to get array of selected images, but it's missing. From your code I can see it's "selectedImages". 
Maybe, you should bring it back or change Readme.
Thanks.

**Comment by yashsharan** [comment]
Same issue faced by me..can you tell me what code did you use instead ?

**Comment by ysoftware** [comment]
@yashsharan just use "selectedImages" instead. I tested, it works.

**Comment by yashsharan** [comment]
@ysoftware so instead of ImagePickerActivity.INTENT_EXTRA_SELECTED_IMAGES i should write selectedImages right?

**Comment by ysoftware** [comment]
@yashsharan 
ArrayList<Image> images = data.getParcelableArrayListExtra("selectedImages");

**Comment by yashsharan** [comment]
@ysoftware it only works with ArrayList not ArrayList<Image> type

**Comment by esafirm** [comment]
@ysoftware will check it soon.

BTW, why don't you just use the helper method?
```
ArrayList<Image> images = (ArrayList<Image>) ImagePicker.getImages(data);
```

**Comment by codeInCamelCase** [comment]
@esafirm half the time my half of the images in the gallery are not rendering(just showing grey image instead of the image).. I thought maybe if I try the intent method it would solve my problem.. I'm running android 7.1.1

**Comment by yashsharan** [comment]
@esafirm half the time my half of the images in the gallery are not rendering(just showing grey image instead of the image).. I thought maybe if I try the intent method it would solve my problem.. I'm running android 7.1.1

**Comment by ysoftware** [comment]
@esafirm I'm creating ImagePicker with Intent and processing data in onActivityResult.

**Comment by esafirm** [comment]
@ysoftware It's doesn't matter if you use intent or `ImagePicker.start()`
You can get your images in `onActivityResult` using

```
ArrayList<Image> images = (ArrayList<Image>) ImagePicker.getImages(data);
```

**Comment by ysoftware** [comment]
@esafirm oh great. Thank you.
