### ISSUE TITLE
Anyway to choose default camera, when user has different type of camera app?

### ISSUE THREAD

**Issue by immimu** [esafirm/android-image-picker#200]

**Comment by esafirm** [comment]
What do you mean? The camera action is simply firing Camera intent
So if there's another camera app, you can choose it from the intent chooser right?

**Comment by AldioFirando** [comment]
I'm also find issue like this, for some reason in some device brand when firing Camera just open the default camera even they have another camera installed in their device,, so the chooser is not show,,
any idea about this?

**Comment by esafirm** [comment]
Unless you can comes up with a PR I'm closing this because dealing with custom intent will add more responsibility (and headache)
