### ISSUE TITLE
Double/duplicate image after taking picture from camera

### ISSUE THREAD

**Issue by hendrawd** [esafirm/android-image-picker#204]
## Expected Behavior
It should create only 1 image

## Actual Behavior
2 images created at the same time after taking picture

## Steps to Reproduce the Problem

  1. Open image picker with code below 
```
ImagePicker
    .create(this@SomeActivity)
    .theme(R.style.ImagePickerTheme)
    .single()
    .start()
```

  2. Tap camera action menu button at the top right corner of the screen
![screenshot 1551208323768](https://user-images.githubusercontent.com/9481791/53440414-0c91ba00-3a37-11e9-9637-02878161dd95.jpg)

  3. Take a photo and press the positive button
![screenshot-1551208466972](https://user-images.githubusercontent.com/9481791/53440434-17e4e580-3a37-11e9-89fa-5bf6605d6a29.jpg)

  4. The photo will be duplicated/double
![screenshot 1551208480366](https://user-images.githubusercontent.com/9481791/53440446-1e735d00-3a37-11e9-8477-8efac076addf.jpg)

## Specifications

  - Image Picker Version: 1.13.1
  - Android OS: 7.0(With custom OS: XOS Hummingbird v3.1.0)
  - Phone: Infinix Zero 5(Model: Infinix X603)

**Comment by ricardosousaDev** [comment]
Hi @hendrawd @esafirm - I've created a pull-request to solve this issue.

**Comment by esafirm** [comment]
Hi @hendrawd can you please check https://github.com/esafirm/android-image-picker/releases/tag/2.1.0 ?

It makes the image picker only passing the `File` without crating it.

**Comment by hendrawd** [comment]
Sorry for the late response, I am doing it now

**Comment by hendrawd** [comment]
The bug still reproducible

**Comment by hendrawd** [comment]
Just for your information that the image saved to 2 directories:
- root/Picture/Camera
- root/DCIM/Camera

**Comment by AmosKorir** [comment]
Any Solution for this Issue? I am facing the same issue with version 2.2.0 in Infinix android 8 but fine in android 10

**Comment by esafirm** [comment]
@AmosKorir i guess this is due to the camera app itself, `EXTRA_OUTPUT` should override the original output. 
Have you tried a different camera app? 

Meanwhile, i'm gonna recreate https://github.com/esafirm/android-image-picker/pull/211 to make it more library friendly

**Comment by AmosKorir** [comment]
Actually this is an issue with the installed camera App
