### ISSUE TITLE
esafirm filed to add in android  project

### ISSUE THREAD

**Issue by jaythanki425** [esafirm/android-image-picker#205]
## Steps to Reproduce the Problem
  1.ERROR : Failed to resolve: com.github.esafirm.android-image-picker:imagepicker:2.0.0 
  2.ERROR : Failed to resolve: com.github.esafirm.android-image-picker:rximagepicker:2.0.0

 

# Specifications
  - Image Picker Version:2.0.0
  - Android OS:6.0
  - Phone:lenovo k5 note

**Comment by pawanasati1990** [comment]
Me too

**Comment by esafirm** [comment]
It's available in Jitpack. Maybe the server down when you try to sync it. 
Can you please try again?
