### ISSUE TITLE
When will 1.13.1 become available?

### ISSUE THREAD

**Issue by okadan** [esafirm/android-image-picker#207]
@esafirm 

Currently, version 1.13.1 seems to be unavailable. #199 

When will it become available?

**Comment by esafirm** [comment]
Sorry, it won't be available since re-publish in Jitpack is not as easy as it looks. 
You can use version 1.13.0 or 2.0.0 instead.

**Comment by joshfriend** [comment]
https://github.com/jitpack/jitpack.io/issues/3797
https://github.com/jitpack/jitpack.io/issues/3757
https://github.com/jitpack/jitpack.io/issues/3744
https://github.com/jitpack/jitpack.io/issues/3605

How did this version become broken? I had been using it successfully since July 26 2018

**Comment by joshfriend** [comment]
Supposedly you can remove build results if you own the project: https://github.com/jitpack/jitpack.io/issues/45#issuecomment-105171695

**Comment by joshfriend** [comment]
It's back!
