### ISSUE TITLE
> More than one file was found with OS independent path 'META-INF/androidx.legacy_legacy-support-core-utils.version'

### ISSUE THREAD

**Issue by AnjaniJoshi** [esafirm/android-image-picker#209]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> More than one file was found with OS independent path 'META-INF/androidx.legacy_legacy-support-core-utils.version'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
29 actionable tasks: 24 executed, 5 up-to-date

**Comment by esafirm** [comment]
Have you tried this @AnjaniJoshi ?

https://stackoverflow.com/questions/44342455/more-than-one-file-was-found-with-os-independent-path-meta-inf-license

**Comment by AnjaniJoshi** [comment]
Yes but not resolved yet .

**Comment by esafirm** [comment]
I personally think exclude line below will solve the problem

```
exclude 'META-INF/androidx.legacy_legacy-support-core-utils.version'
```
 
Will try this later in sample project. 

Can you give me your dependency list?

**Comment by iamsardorbek** [comment]
Dear esafirm, I tried the exclude line 

`exclude 'META-INF/androidx.legacy_legacy-support-core-utils.version'`

However, it did not work. What else can I do?

My dependencies list (from build.gradle (Module:app)):
`dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    implementation 'androidx.cardview:cardview:1.0.0'
}`

**Comment by zawawimanja** [comment]
same with me.before this the project is ok. but now cannot build it.

**Comment by esafirm** [comment]
This is obviously an issue in the artifact merger. Will closing this because it's in the scope of library issue
