### ISSUE TITLE
returned Data is null

### ISSUE THREAD

**Issue by mermaidshop** [esafirm/android-image-picker#212]
Returned data is null in both Camera only/Files picking modes.

## Specifications

  - Image Picker Version: 1.13.1
  - Android OS: 8.1.0
  - Phone: huawei y5 prime 2018

**Comment by sajjadjaved01** [comment]
When selecting image the data is returns Null, & also selecting the selected Img return null also. 
This works in Android Ver 6 but not working in 9.

**Comment by husseinyassine25** [comment]
Problem still persists

**Comment by esafirm** [comment]
Can you please attach samples on how to reproduce this? Thank you

**Comment by esafirm** [comment]
`uri.getData()` is deprecated
