### ISSUE TITLE
Error when build

### ISSUE THREAD

**Issue by stephendaniel** [esafirm/android-image-picker#217]
Hi, I tried to integrate android image picker to my project, I am using android-image-picker version 2.0.0, but unfortunately I failed to do so. When I tried to build the app, this error will be shown :

```
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:10:5-34:19 to override.
```

**Comment by yasirahmedkhan** [comment]
> 
> 
> Hi, I tried to integrate android image picker to my project, I am using android-image-picker version 2.0.0, but unfortunately I failed to do so. When I tried to build the app, this error will be shown :
> 
> ```
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
> 	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
> 	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:10:5-34:19 to override.
> ```

same issue

**Comment by reizamv** [comment]
this happen because this library in androidx maybe lower version 1.8 ....but i want an update version that support appcompat

**Comment by reizamv** [comment]
just migrate to androidx is better and no error

**Comment by maghfirzakir** [comment]
> Hi, I tried to integrate android image picker to my project, I am using android-image-picker version 2.0.0, but unfortunately I failed to do so. When I tried to build the app, this error will be shown :
> 
> ```
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
> 	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
> 	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:10:5-34:19 to override.
> ```

same issue.

**Comment by inyomanw** [comment]
> Hi, I tried to integrate android image picker to my project, I am using android-image-picker version 2.0.0, but unfortunately I failed to do so. When I tried to build the app, this error will be shown :
> 
> ```
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
> 	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
> 	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:10:5-34:19 to override.
> ```

same issue
