### ISSUE TITLE
RecyclerView no adapter attached error

### ISSUE THREAD

**Issue by addy419** [esafirm/android-image-picker#223]
## Expected Behavior
Adapter should be already binded with RecyclerView
`public void setImageAdapter(List<Image> images) {
        imageAdapter.setData(images);
        setItemDecoration(imageColumns);
        recyclerView.setAdapter(imageAdapter);
    }`

## Actual Behavior
`E/RecyclerView: No adapter attached; skipping layout`

## Specifications

  - Image Picker Version: 2.0.0
  - Android OS: 9
  - Phone: Android SDK Built for x86

**Comment by addy419** [comment]
Nervermind, Adding `intent.putExtra(ImagePickerConfig.class.getSimpleName(), config);` solved it.

**Comment by addy419** [comment]
This issue still occurs occasionally. I can't find a solution.

**Comment by esafirm** [comment]
@addy419 hey it's been a while, can you confirm the issue still exist in our newest version?
If yes, can you make some sample app that can reproduce this issue?

**Comment by addy419** [comment]
@esafirm I don't have my files as of now, from what I remember, it was a glide issue. I'm sorry about the inconvenience. I'll close the issue.

**Comment by Fredrick422** [comment]
Would you mind explain how glide would cause the issue, because I am still facing this problem
