### ISSUE TITLE
build error after upgrading to 2.0.0 from 1.13.1

### ISSUE THREAD

**Issue by Pranoyenjamuri** [esafirm/android-image-picker#224]
## Expected Behavior
Build should be a success

## Actual Behavior
The Android build is not recognizing "kotlinx.android.synthetic.main" and throwing a lot of errors

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Image Picker Version:
  - Android OS:
  - Phone:

**Comment by Pranoyenjamuri** [comment]
Please help us..

**Comment by esafirm** [comment]
@Pranoyenjamuri i'm not really sure about this. Maybe AndroidX compatibility issue?
