### ISSUE TITLE
Cannot add version 2.0.0

### ISSUE THREAD

**Issue by amir14a** [esafirm/android-image-picker#226]
this Error happen when use v2.0.0:

Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:11:5-49:19 to override.

  - Image Picker Version:2.0.0
  - Android OS:23
  - Phone:

**Comment by esafirm** [comment]
I think this happen because your projects haven't yet migrate to AndroidX 

Can you try adding these two lines in `gradle.properties`

```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by esafirm** [comment]
Closing the issue do inactivity. 
Will add some info in readme
