### ISSUE TITLE
Multiple image capture

### ISSUE THREAD

**Issue by yasserakbbach** [esafirm/android-image-picker#232]
## Expected Behavior
When tap to capture image (using Camera) I wanna capture multiple images then gets selected automatically

## Actual Behavior
It provides you with a confirmation to either accept the image or not (it depends on the phone's brand)

## Specifications

  - Image Picker Version: 2.0.0
  - Android OS: Oreo
  - Phone: OPPO

**Comment by esafirm** [comment]
Well, this is the limitation of this library. It doesn't use a custom camera capture component. Only camera intent (for now)
