### ISSUE TITLE
Hi, is there anyway to user image picker with Glide 4.8.0

### ISSUE THREAD

**Issue by incomingflyingbrick** [esafirm/android-image-picker#233]
I am using Glide 4.8.0 in my project and I can't change the version because some other module of the app is also using Glide 4.8.0. Is there anyway I could change the glide version of Image Picker? Thank you!

**Comment by esafirm** [comment]
You could exclude `Glide` from this libs. Or set a resolution strategy 

More on this: 
https://discuss.gradle.org/t/how-do-i-exclude-specific-transitive-dependencies-of-something-i-depend-on/17991
