### ISSUE TITLE
Add request code 

### ISSUE THREAD

**Issue by ShahadatShaki** [esafirm/android-image-picker#234]
I have two imageview, Now I want to chose which image goes where. As you hardcoded the request code, We can't determine which imageview should we show the image. Hope you understand the problem ..

**Comment by esafirm** [comment]
You can start the Image picker with your own request code. 
ex: 

```java
ImagePicker.create(this).start(yourRequestCode)
```

**Comment by ShahadatShaki** [comment]
Please add this on your doc.. Thanks.. 😀 😀
