### ISSUE TITLE
How to get selected videos?

### ISSUE THREAD

**Issue by iskugor** [esafirm/android-image-picker#235]
Hello!

If I enable selection of videos, I can select them, but how can I get them in result?

I can see there's only function to get images:

`List<Image> images = ImagePicker.getImages(data);`

## Specifications

  - Image Picker Version: 2.1.0

**Comment by juange87** [comment]
The video file is returned inside the object `Image`

You can create a extension function for this object to check if the file is a video:

```
fun com.esafirm.imagepicker.model.Image.isVideo(): Boolean {
    return this.name.endsWith(".mp4")
}

```

/c @esafirm
