### ISSUE TITLE
ActivityNotFoundException 

### ISSUE THREAD

**Issue by achinverma** [esafirm/android-image-picker#236]
Hi , I have used this library and i am getting below error:

implementation 'com.github.esafirm.android-image-picker:imagepicker:2.1.0'

android.content.ActivityNotFoundException: Unable to find explicit activity class {com.app.sales_chap/com.esafirm.imagepicker.features.ImagePickerActivity}; have you declared this activity in your AndroidManifest.xml?

**Comment by esafirm** [comment]
I'm closing this for now.
Can you please check if the issue still exists on the new version?
