### ISSUE TITLE
On Device with lot of Images, Image Picker is slow to load

### ISSUE THREAD

**Issue by saran2020** [esafirm/android-image-picker#237]
When tested on a device with lot of images ~7000 it took about 5 seconds to display result. After removing the line `File file = makeSafeFile(path)`[(Link)](https://github.com/esafirm/android-image-picker/blob/339a4b3348b545c323b2024fc2f65467cc4fcbbd/imagepicker/src/main/java/com/esafirm/imagepicker/features/ImageFileLoader.java#L114) in the ImageFileLoader displayed results in about 2 seconds.

**Comment by edgarscr** [comment]
i had the same problem can u help us?

**Comment by saran2020** [comment]
@edgarscr what I have done is, I cloned the repo and imported the library into my project as a module and removed those lines as well as made several other changes.

**Comment by edgarscr** [comment]
what lines we have to remove? i dont know how i can add this library as module can u help me?

**Comment by saran2020** [comment]
To add a library as a module, on Android Studio select File -> New -> Import Module and import the  imagepicker module of this library. (There are 3 modules in the code of this library. 1. `sample` 2. `rximagepicker` 3. `imagepicker`)

Check the issue message to know which line has to be remove.

**Comment by esafirm** [comment]
Hey guys, sorry for the late reply. 
I could make this optional or configurable if you want.

Probably will make this configurable.
