### ISSUE TITLE
Module depends on one or more Android libraries

### ISSUE THREAD

**Issue by haideralipunjabi** [esafirm/android-image-picker#24]
Error:Module 'com.github.esafirm.android-image-picker:imagepicker:1.3.0' depends on one or more Android Libraries but is a jar

**Comment by ammarasim** [comment]
facing the same issue

**Comment by haideralipunjabi** [comment]
I do apologies for not Googling the issue properly. I saw many Github Repositories of different libraries having the same issue, so I thought it was an error from the code. But, I found a fix by googling more deeply.
My original build.gradle entry
`compile 'com.github.esafirm.android-image-picker:imagepicker:1.3.2'`

and changed it to
`compile 'com.github.esafirm.android-image-picker:imagepicker:1.3.2@aar'` 

@ammarasim 
Just add the @aar at the end

**Comment by esafirm** [comment]
Readme updated 😊

**Comment by deluakin** [comment]
Had the same issue, but that solved it. Thanks
