### ISSUE TITLE
Does not ask for permission, and no app options called - in 2.1.0

### ISSUE THREAD

**Issue by djdance** [esafirm/android-image-picker#241]
## Expected Behavior
ask user for 2 permissions automatically on 1st start. Or at least call app prefs on hint.

## Actual Behavior
Shows white activity, with bottom toast (not clickable! although it was in 1.13.1), also with camera menu. No any auto dialogs. Need to click on Camera manually, that's bad.

## Steps to Reproduce the Problem

  1. create app with no permissions in Manifest
  2. do ImagePicker.create(this)
  3. get the result as on the shot. "OK" is non-clickable. 

![device-2019-09-13-220027](https://user-images.githubusercontent.com/2269720/64887879-41cbc580-d672-11e9-9edc-75cd7c5134e3.png)

## Specifications

  - Image Picker Version:2.1.0
  - Android OS: 8
  - Phone: samsung7
- app compileSdkVersion/targetSdkVersion 28

**Comment by esafirm** [comment]
> Need to click on Camera manually, that's bad.

Can you elaborate more on this?

**Comment by djdance** [comment]
I just have tried 2.2.0, the issue is the same, unfortunately. Shot is the same as above. Completely white.

1. user has to do 1 extra click on Camera button to call Permissions dialog. I want this dialog to appear automatically right on page opening. Thus must be no confusing white screen on the picker start. Please fill that white screen, it is not right. 

2. Bottom snackbar is not clickable since 2.1.0. "OK" Button is not clickable. It is a bug, please fix. It worked in 1.13.1

2b. "OK" must call Camera/Storage Permissions dialog, not app's properties.

3. Finally, snackbar text is cropped and doesn't reflect whats going on. Why storage? What storage? It must ask for camera first, not storage. I understand why, but users complain me that I am collecting theirs data from storage :-)

**Comment by djdance** [comment]
Moreover, in all versions if you allow photo and deny storage, and stop ask anymore, **Camera button wont work anymore!** Steps to reproduce:

- uninstall the app, install, call Image picker
- in Permissions dialog: allow photo, deny storage. Recall picker
- again deny storage, check "stop asking me" checkbox. Recall picker
- no popups, white screen, Camera btn does nothing except snackbar
- and snackbar is not clickable in 2.1.0! user is stucked forever until he uninstall the app.

In the other words, you have to respect both camera&storage permission "ExplanationNeeded" states, not only 1st one.

**Comment by onirban27** [comment]
same thing happening on my Samsung A10. i have to set permission from the app settings. it wont ask for permission and shows a bottom sheet with ok button. clicking on the ok button as no effect.

**Comment by djdance** [comment]
so, nothing changed for half a year?
2.2.0 still doesn't ask permissions on android 8. Well, actually, it asks, but snackbar is not clickable.

It starts to ask only on android 10....so it's a pity, but I'm still on 1.13.0

**Comment by adityaism** [comment]
Same problem. It doesn't work.
