### ISSUE TITLE
Error setup ImagePicker from library

### ISSUE THREAD

**Issue by krongnang** [esafirm/android-image-picker#244]
## Expected Behavior
- Open picker

## Actual Behavior
- App crash immediate

## Steps to Reproduce the Problem
 - Just open

## Specifications

  - Image Picker Version: 2.1.0
  - Android OS:EMUI 9.1.0
  - Phone: Huaweid nova 3i

## Error log
https://imgur.com/a/id7oRWd

**Comment by pascalguizard** [comment]
I have the same error with :
- OnePlus 6 (android 9)
- Image Picker Version: 2.1.0
- glide:4.10.0

**Comment by pascalguizard** [comment]
To solve your issue you can use the [original Image Picker](https://github.com/nguyenhoanglam/ImagePicker)

It's work good for me

**Comment by esafirm** [comment]
Can you confirm the issue still remain on 2.3.0 @pascalguizard @krongnang ?
