### ISSUE TITLE
landscape mode 

### ISSUE THREAD

**Issue by daniyalsalim94** [esafirm/android-image-picker#250]
## Expected Behavior
How to open this picker in landscape mode

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Image Picker Version:
  - Android OS:
  - Phone:

**Comment by esafirm** [comment]
@daniyalsalim94 i don't think we have orientation lock, so you just have to set the device orientation to landscape. 

In fact, we support landscape mode quite well
<img width="956" alt="Screen Shot 2020-05-22 at 12 12 39" src="https://user-images.githubusercontent.com/1691440/82633597-b1447c80-9c25-11ea-9ec7-80a29c3e0c0c.png">
