### ISSUE TITLE
Image is rotated.

### ISSUE THREAD

**Issue by elvinakhundzada** [esafirm/android-image-picker#256]
Everything works fine, but when I pick an image from physical device's "Camera" folder, I get that image as rotated. How could this be fixed ? 

I'm using version 2.2.0 and Glide v4.10.0.

**Comment by esafirm** [comment]
@elvinakhundzada This should be handled by `Glide` but if your issue still exists you can use custom image loader like this:
https://github.com/esafirm/android-image-picker/blob/master/sample/src/main/java/com/esafirm/sample/MainActivity.java#L99
