### ISSUE TITLE
can't use custom imageloader

### ISSUE THREAD

**Issue by androidPixl** [esafirm/android-image-picker#257]
Hello
As I see in docs,  to use custom ImageLoader, need to do that
ImagePicker.create(activity).imageLoader(ImageLoader customImageLoader)
but don't exist public method imageLoader(), see screenshot https://prnt.sc/qfgbj5.
I.m using 2.2.0 version of library
What need to do to set ImageLoader?
Thanks

**Comment by esafirm** [comment]
Hi @androidPixl
Sorry, the docs kinda messy right now. You can use `ImagePickerComponentHolder` for custom image loader

Sample: 
https://github.com/esafirm/android-image-picker/blob/master/sample/src/main/java/com/esafirm/sample/MainActivity.java#L99
