### ISSUE TITLE
Send image using retrofit

### ISSUE THREAD

**Issue by rajvijay68** [esafirm/android-image-picker#259]
How do we send the returned Image object from getFirstImageOrNull using retrofit?

Can we get the path (or) File object of this image?

**Comment by PiwanSama** [comment]
Use image.getPath() to get the image path

**Comment by rajvijay68** [comment]
Thank you @PiwanSama .
I used 
```
File file = new File(image.getPath).
RequestBody fileToUpload = RequestBody.create(MediaType.parse("*/*"),file);

```

**Comment by esafirm** [comment]
If anyone trying to figure out get the image from a URI, please refer to this https://github.com/esafirm/android-image-picker/issues/307#issuecomment-1320995444
