### ISSUE TITLE
Android10 scope storage is not Compatible

### ISSUE THREAD

**Issue by xiaowangjunfighting** [esafirm/android-image-picker#263]
## Expected Behavior
public interface ImageLoader {
    void loadImage(Image image, ImageView imageView, ImageType imageType);
}
Due to the compatibility of android10, the load of pictures requires uri. I want the parameter type to be Image, which may be more extensibility.

## Actual Behavior
public interface ImageLoader {
    void loadImage(String path, ImageView imageView, ImageType imageType);
}

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Image Picker Version:2.2.0
  - Android OS: 10
  - Phone:

**Comment by djdance** [comment]
as for me, both shots and gallery don't work on android10, both on 1x and 2x versions of the Picker

**Comment by djdance** [comment]
ah, that's target 29. This helped.https://github.com/esafirm/android-image-picker/issues/258

**Comment by xiaowangjunfighting** [comment]
> ah, that's target 29. This helped.#258

Official documents suggest that all Android 10 and above devices must support scope storage in the future. Even if the targetdkversion or attribute android: requestLegacyExternalStorage is modified, we have to deal with it early

**Comment by ahelen** [comment]
Is the team (somebody) already working on this issue? When will an update be released?
