### ISSUE TITLE
Android 7 Meizu M5 Note the application freezes and then closes

### ISSUE THREAD

**Issue by Strikelon** [esafirm/android-image-picker#264]
## Expected Behavior
After the user selects a picture, he returns to the application and it does not freeze

## Actual Behavior
After the user selects a picture, he returns to the application and aplications begin to freezes and then closes. This happens even if I don’t display selected image in ImageView

## Steps to Reproduce the Problem

  1.  User selected Image
  2. After onActivityResult aplications begin to freezes and then closes

## Specifications

  - Image Picker Version: 2.0.0'
  - Android OS: 7
  - Phone: Meizy M5 Note

**Comment by Strikelon** [comment]
Hello everyone. In general, I found that the hang on this phone model ceases to occur if you remove the line // .includeVideo (true). I wanted to use this library for both pictures and videos.

**Comment by esafirm** [comment]
@Strikelon is there any log or stacktrace?

**Comment by esafirm** [comment]
Closing this due inactivity
