### ISSUE TITLE
Progressbar bug

### ISSUE THREAD

**Issue by miladsalimiiii** [esafirm/android-image-picker#265]
## Expected Behavior
Progressbar after all images loaded didnt show again.

## Actual Behavior
Some times after all images loaded progressbar appear and start to progress.

## Specifications

  - Image Picker Version:2.2.0
  - Android OS:7.0
  - Phone:Galexy S7

**Comment by esafirm** [comment]
This should not exist in 3.0.0 or the latest 2.x version
