### ISSUE TITLE
Does not show external images into Gallery

### ISSUE THREAD

**Issue by miladsalimiiii** [esafirm/android-image-picker#266]
## Expected Behavior
Show external images into Gallery

## Actual Behavior
Does not show external images into Gallery

## Specifications

  - Image Picker Version:2.2.0
  - Android OS:7
  - Phone:Galexy S7

**Comment by ahmed7official** [comment]
same problem with me

**Comment by miladsalimiiii** [comment]
> same problem with me
> 
> ==================================
> **update:**
> 
> **solved** by add `android:requestLegacyExternalStorage="true"` to manifest

Thank you i will test it.
