### ISSUE TITLE
When i have select 100 images screen comes black for few minutes

### ISSUE THREAD

**Issue by karanbeer287** [esafirm/android-image-picker#267]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Image Picker Version:
  - Android OS:
  - Phone:

**Comment by dekanako** [comment]
hey bro can you tell me how I can select multiple messages
that's my code

`ImagePicker.Companion.with(fragment)
                .crop()
                .compress(500)
                .cameraOnly()
                .start();`
