### ISSUE TITLE
Show the video duration

### ISSUE THREAD

**Issue by xpdlf1004** [esafirm/android-image-picker#270]
I changed the label "Video" to the duration of the video file.
Because there were some requesting issues and I needed it too. :)
The duration is sufficient to suggest the video. Also I think it is distinct from "GIF".

Please review my PR :)

- Show the duration label as HH:mm:ss or mm:ss format.

#### Related issues
https://github.com/esafirm/android-image-picker/issues/134
https://github.com/esafirm/android-image-picker/issues/213

**Comment by esafirm** [comment]
Merged ❤️
