### ISSUE TITLE
Image Data Class should have file uri

### ISSUE THREAD

**Issue by anupdey99** [esafirm/android-image-picker#278]
Image class should have uri of the file. 
I came across a problem where the the uri of the file not the path!
Then I have to Query the uri from path
Like this
MediaScannerConnection.scanFile(requireContext(), arrayOf(it), null) { path, uri ->
    Timber.d("uri: $uri")
 }

Adding uri of file in the Image data class may be a good addition to this library
Thanks for awesome library :)

**Comment by esafirm** [comment]
Valid use case. Will add this on the next release

**Comment by esafirm** [comment]
@anupdey99 i think you also could create the uri from our current `Image` object with 

```kotlin
ContentUris.withAppendedId(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, image.getId())
```

**Comment by anupdey99** [comment]
Thanks. Appreciate it
