### ISSUE TITLE
Bug: It Shows "No Images Found" in Android 10

### ISSUE THREAD

**Issue by ydhnwb** [esafirm/android-image-picker#279]
## Permission
The storage permission is allowed. But still shows No images found. I try to use "requestLegacyStorage" in manifests.xml, still shows No Images Found

## Screenshot
![Screenshot_20200622-191841](https://user-images.githubusercontent.com/26734262/85287153-0e01b400-b4be-11ea-9271-ec1496120fe0.jpg)

## Specifications

  - Image Picker Version: 2.3.1
  - Android OS: 10 Q
  - Phone: Mi A2

**Comment by hoajb** [comment]
Check Nightfright's comment on  #280. It worked for me

**Comment by esafirm** [comment]
This should be fixed in https://github.com/esafirm/android-image-picker/releases/tag/2.4.0
