### ISSUE TITLE
App Crashed [Update Readme]

### ISSUE THREAD

**Issue by pinvisible** [esafirm/android-image-picker#28]
I am using below intent code and getting force close.

# Source Code
-------------------------------------------
Intent intent = new Intent(mActivity, ImagePickerActivity.class);

        intent.putExtra(ImagePicker.EXTRA_FOLDER_MODE, true);
        intent.putExtra(ImagePicker.EXTRA_MODE, ImagePicker.MODE_SINGLE);
        intent.putExtra(ImagePicker.EXTRA_LIMIT, 1);
        intent.putExtra(ImagePicker.EXTRA_SHOW_CAMERA, true);
        intent.putExtra(ImagePicker.EXTRA_FOLDER_TITLE, "Album");
        intent.putExtra(ImagePicker.EXTRA_IMAGE_TITLE, "Tap to select images");
        intent.putExtra(ImagePicker.EXTRA_IMAGE_DIRECTORY, "Camera");
        intent.putExtra(ImagePicker.EXTRA_RETURN_AFTER_FIRST, true); //default is false

        startActivityForResult(intent, 1234);

# Output
-------------------------------------------
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       java.lang.NoClassDefFoundError: com.bumptech.glide.Glide
                                                                           at com.esafirm.imagepicker.adapter.FolderPickerAdapter.onBindViewHolder(FolderPickerAdapter.java:46)
                                                                           at com.esafirm.imagepicker.adapter.FolderPickerAdapter.onBindViewHolder(FolderPickerAdapter.java:21)
                                                                           at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6067)

**Comment by esafirm** [comment]
@pinvisible have you tried adding `@aar` as prefix in your gradle declaration?

**Comment by pinvisible** [comment]
Yes. I have used below code.

compile 'com.github.esafirm.android-image-picker:imagepicker:1.3.3@aar'
    // for experimental rx picker
compile 'com.github.esafirm.android-image-picker:rximagepicker:1.3.3@aar'

**Comment by Makingweb** [comment]
Same issure

**Comment by esafirm** [comment]
Hi sorry for the really late answer. You can add `Glide` to your `build.gradle`

```java
  compile 'com.github.bumptech.glide:glide:3.7.0'
```

IDK why it's not included in the first place

**Comment by maxxx** [comment]
It helps. Dev, please update readme and include Glide.

**Comment by esafirm** [comment]
@maxxx Done 👍
