### ISSUE TITLE
Gradle build not working (esafirm 502 server error)

### ISSUE THREAD

**Issue by usmanokara** [esafirm/android-image-picker#286]
## Actual Behavior

Could not HEAD 'https://bintray.com/rameshbhupathi/maven/com/github/esafirm/android-image-picker/2.0.0/android-image-picker-2.0.0.pom'. Received status code 502 from server: Bad Gateway

## Steps to Reproduce the Problem

  1. clean project
2. rebuild project with esafirm (image picker)

## Specifications
  - Image Picker Version:
  - Android OS:

**Comment by esafirm** [comment]
You should use Jitpack, not Bintray :(
