### ISSUE TITLE
Cannot save taken picture on Android Q

### ISSUE THREAD

**Issue by jmich41** [esafirm/android-image-picker#292]
## Expected Behavior
After taking a picture see the picture on the gallery list

## Actual Behavior
After taking a picture, app back to gallery list, but the new picture is missing

## Steps to Reproduce the Problem

  1. Downloaded your sample app
  2. Nothing changes simple run the sample
  3. Click "Pick Image"
  4. Click icon "Take Picture" and take the picture, app backs to gallery
  5. App shows the gallery and there is no new picture

We have this situation also on in our app, but in the sample app is the same situation.

## Specifications

  - Image Picker Version: 2.3.2 
  - Android OS: Android 11
  - Phone: Pixel 3a

**Comment by hjchin** [comment]
it is already resolved in PR #290, available in v2.4 https://github.com/esafirm/android-image-picker/releases/tag/2.4.0
