### ISSUE TITLE
What about permissions?

### ISSUE THREAD

**Issue by Rainer-Lang** [esafirm/android-image-picker#3]

**Comment by esafirm** [comment]
Android runtime permissions prior to Android M is already handled inside the library.

**Comment by Rainer-Lang** [comment]
Thanks

**Comment by long1eu** [comment]
I don't see this for android.permission.READ_EXTERNAL_STORAGE if I want to use only camera.

**Comment by esafirm** [comment]
@long1eu it is because we get the images from `MediaStore.Images.Media.EXTERNAL_CONTENT_URI` 

I don't know why i have the permission lying around the manifest.
