### ISSUE TITLE
CameraIntent - Android 10 - ImagePickerFragment - Intent data [null]

### ISSUE THREAD

**Issue by hoordev** [esafirm/android-image-picker#305]
![image](https://user-images.githubusercontent.com/4958355/96118960-8e747680-0eec-11eb-8323-645851fe7bcf.png)
![image](https://user-images.githubusercontent.com/4958355/96119034-aa781800-0eec-11eb-9f74-530d579a92b0.png)
![image](https://user-images.githubusercontent.com/4958355/96119065-b49a1680-0eec-11eb-9325-b5a82f52d289.png)

Tested and same results at:
- Samsung Galaxy S9 Plus - Android 10 - OneUI 2.0
- Huawei P40 Lite - Android 10 - EMUI 10.1.0

**Comment by esafirm** [comment]
It should be fixed in https://github.com/esafirm/android-image-picker/pull/302
Can you check the snapshot?

**Comment by hoordev** [comment]
Snapshot by jitpack.io
Build log [build.log](https://github.com/esafirm/android-image-picker/files/5390546/build.log)

After capture the photo with the built in camera app and I taped the ok button, then closed native camera app and i saw white screen only.

Still tested on s9 and p40 lite

**Comment by esafirm** [comment]
@hoordev that's strange. will check on it later
Meanwhile, is there any log that might help?

**Comment by esafirm** [comment]
This is now fixed in https://github.com/esafirm/android-image-picker/pull/306

**Comment by esafirm** [comment]
This is now available in https://github.com/esafirm/android-image-picker/releases/tag/2.4.1

**Comment by hoordev** [comment]
Tested the new 2.4.1 version and when captured the photo I got a nothing(?)

![20201020-111057](https://user-images.githubusercontent.com/4958355/96566522-f6003c80-12c5-11eb-8a06-fd1eb3e18fec.gif)
