### ISSUE TITLE
Image path cant convert to file in Android 10 or above

### ISSUE THREAD

**Issue by shaon2016** [esafirm/android-image-picker#307]
## Expected Behavior
Below Android 10. It is fine. 
I can convert image to file using image path 

## Actual Behavior
I can't convert image to file using image path in android 10 above version.

## Steps to Reproduce the Problem

  1.  After choosing the image, I convert image to file using this below code

```
File(images[0].path)
```
It throws this exception

java.io.FileNotFoundException: /storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20201021-WA0002.jpg: open failed: EACCES (Permission denied)

 Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)

## Specifications

  - Image Picker Version: 2.4.0
  - Android OS:  Android  10  
  - Phone: Samsung Galaxy j6

**Comment by hoordev** [comment]
Same problem and mention at [305](https://github.com/esafirm/android-image-picker/issues/305#issuecomment-712715069)

**Comment by shaon2016** [comment]
@hoordev After this problem, I have created my own library. and found out a solution and implemented it.......

https://github.com/shaon2016/ProPicker

Using stream from the uri we can convert it to a file then use it..
or we can use the image as byte array to upload.. 

I have implemented it in my library

**Comment by Nightfright** [comment]
I checked and the uri was correct when path was wrong in android 10 so I made something like this to fetch working filepath if you don't want to use the uri

`private String getFilePathFromImage(Image image) {
        if (image == null)
            return null;

        if (!TextUtils.isEmpty(image.getPath()) && new File(image.getPath()).exists()) {
            return image.getPath();
        } else if (image.getUri() != null) {
            String[] filePathColumn = {MediaStore.Images.Media.DATA};
            
            Cursor cursor = requireActivity().getContentResolver().query(image.getUri(),
                    filePathColumn, null, null, null);
            
            cursor.moveToFirst();
            int columnIndex = cursor.getColumnIndex(filePathColumn[0]);
            String imgFilePath = null;
            if (columnIndex != -1) {
                imgFilePath = cursor.getString(columnIndex);
            }
            cursor.close();
            return imgFilePath;
        }
        return null;
    }`

**Comment by esafirm** [comment]
The only safe way to access the data of the image is through `Uri`. As @shaon2016 said, you could use content resolver to [resolve the data](https://github.com/shaon2016/ProPicker/blob/d141548e64730c8eb798e5bf365060f114bbdc58/propicker/src/main/java/com/shaon2016/propicker/pro_image_picker/ProPicker.kt#L74)

Something like this
```kotlin
val byteArray = context.contentResolver.openInputStream(it.uri)?.readBytes()
``` 

Another way to do it is using image loader like `Glide`

```kotlin
Glide.with(applicationContext).load(uri).listener(...).submit()
```

Hope it helps!
