### ISSUE TITLE
how can order the folder?

### ISSUE THREAD

**Issue by design365** [esafirm/android-image-picker#308]
My code is :

 ImagePicker.create(ctx)
                       .folderMode(true) // folder mode (false by default)
                       .toolbarFolderTitle("Folder") // folder selection title
                       .toolbarImageTitle("Tap to select") // image selection title
                       .toolbarArrowColor(Color.BLACK) // Toolbar 'up' arrow color
                       .includeVideo(false) // Show video on image picker
                       // Activity or Fragment
                       .start();

some folders show, but I want the Camera folder in the  first. 
how can I do that? 
thanks

**Comment by esafirm** [comment]
There's no easy way for this. You have to create a custom `ImageFileLoader` and set it in `ImagePickerComponentsHolder`
