### ISSUE TITLE
Camera blank image is not deleted !

### ISSUE THREAD

**Issue by mhrlive** [esafirm/android-image-picker#309]
When I open camera, a blank image is created and is not deleted after I get back from camera !

## Steps to Reproduce the Problem
  1.open camera
 2. go back or close App
  3. the blank 0kb image is not removed from storage !

## Specifications

  - Image Picker Version:2.4.1
  - Android OS: 10
  - Phone: Samsung Galaxy s9

**Comment by Nightfright** [comment]
Not sure if this is helpful but I fixed it by changing
ImagePickerFragment.java
`/**
     * Check if the captured image is stored successfully
     * Then reload data
     */
    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == RC_CAPTURE) {
            if (resultCode == RESULT_OK) {
                presenter.finishCaptureImage(getActivity(), data, getBaseConfig());
            } else if (resultCode == RESULT_CANCELED && isCameraOnly) {
                presenter.abortCaptureImage();
                interactionListener.cancel();
            }
        }
    }`
to
` } else if (resultCode == RESULT_CANCELED) { //removed isCameraOnly to get next part to tigger
                presenter.abortCaptureImage(getContext());`

and in
DefaultCameraModule.kt
` val imagePath = currentImagePath ?: return
        val file = File(imagePath)
        if (file.exists()) {
            file.delete()
        } else { //Added this else part since in api29+ we use mediastore we need to remove the canceled row from there.
            val uri = Uri.parse(currentUri)
            context.applicationContext.contentResolver.delete(uri, null, null)
        }`

@esafirm if this is not helpful at all, just delete it, i have not tested this much just trying some quick and dirty changes to get the lib working in api29 and 30 targeting 30 for personal use.

**Comment by esafirm** [comment]
Got it @Nightfright will try to include this on 3.x
