### ISSUE TITLE
onActivityResult, startActivityForResult etc are deprecated now. Is there any alternative?

### ISSUE THREAD

**Issue by Abhishek95872** [esafirm/android-image-picker#314]
As we know startActivityForResult, onActivityResult etc is deprecated in fragment now. I am using this library in my current project which is coded in Java fully. So just wanted to know is there any alternative to avoid using those methods in my current project?

**Comment by lmj0011** [comment]
and here's the [documentation](https://developer.android.com/training/basics/intents/result)

**Comment by lmj0011** [comment]
Moving the functionality of this library into a BottomSheet would be an alternative way 

see this similiar library for example: https://github.com/kroegerama/bottomsheet-imagepicker#step-2-implement-the-callback-handler

**Comment by esafirm** [comment]
It's deprecated in appcompat 1.3.0 which still in beta phase. I'll see what I can do when it becomes stable

**Comment by esafirm** [comment]
We support the new way of getting result in version `3.0.0`. As for bottom sheet, my next plan is to have the picker can have a flexible decorator/container
