### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by basriumar12** [esafirm/android-image-picker#315]
get error com.esafirm.imagepicker.features.fileloader.DefaultImageFileLoader$ImageLoadRunnable.run (DefaultImageFileLoader.java:159)

the message error is Fatal Exception: java.lang.NullPointerException
Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter name
com.esafirm.imagepicker.model.Image.<init>.

how to solve for this?
this happen for vivo android 9

**Comment by esafirm** [comment]
This should be fixed
