### ISSUE TITLE
Option to save to a temp file

### ISSUE THREAD

**Issue by shalevmo** [esafirm/android-image-picker#32]
Hi, 
can you please add an option to save captured image in temp path? like context.getCacheDir();
Maybe even add an option to set the the full directory path. 
Something like these two setters:
setFullDirectoryPath(File dir) / setFullDirectoryPath(String dir)
Thanks.

**Comment by esafirm** [comment]
Hi @shalevmo i know it's been a long time but now you can set the full directory path with
```
ImagePicker.imageFullDirectory(String path)
```

This is available from `1.7.5` 

Cheers! 😬
