### ISSUE TITLE
Some Devices rotate images which are captured using camera

### ISSUE THREAD

**Issue by mhtparyani** [esafirm/android-image-picker#321]
## Expected Behavior
It should return the image without rotation

## Actual Behavior
If the image is captured out of the application and then tried to fetch from the gallery it rotates the image.(Only in some devices)

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Image Picker Version:
  - Android OS:
  - Phone:

**Comment by esafirm** [comment]
The rotation is handled by `Glide` right now. If you want to customize the behavior, you can change the image loader
More info:
https://github.com/esafirm/android-image-picker/blob/master/docs/another_image_library.md
