### ISSUE TITLE
ReturnMode.GALLERY_ONLY still shows icon for Taking photos from Camera

### ISSUE THREAD

**Issue by GolombYotam** [esafirm/android-image-picker#326]
## Expected Behavior
Camera button on top right should not be visible on ReturnMode.GALLERY_ONLY

## Actual Behavior
Camera button on top right should is visible on ReturnMode.GALLERY_ONLY

## Steps to Reproduce the Problem

  1. implement ImagePicker with ReturnMode.GALLERY_ONLY
  2. Open the ImagePicker
  3. Look at top right corner

## Specifications

  - Image Picker Version: 2.4.1
  - Android OS: 10
  - Phone: Emulator or Pixel 3

**Comment by Nightfright** [comment]
.showCamera(false)

returnMode sets if picker should close/return as soon you select one thing.
CAMERA_ONLY = return if you snap a pic
GALLERY_ONLY = return if you select in gallery
ALL = both
none stay in picker until you done selecting/snapping multiple
