### ISSUE TITLE
Changeing the toolbar color

### ISSUE THREAD

**Issue by kozmabalazs** [esafirm/android-image-picker#33]
Is it possible to change the color of the toolbar? Maybe the icons in the toolbar?

I found a place in the theme with the comment customize your theme, but when i build the project it is set back to the defaults of the image picker.

**Comment by wooi** [comment]
override the colors resource file,add this in colors.xml
`<color name="ef_colorPrimary" >YOURCOLOR</color>
    <color name="ef_colorPrimaryDark" >YOURCOLOR</color>`

**Comment by esafirm** [comment]
@kozmabalazs @wooi 

You can override the color resources like @wooi mention
or in `1.5.0` you can use `theme` support like this

```java
ImagePicker imagePicker = ImagePicker.create(this)
  .theme(R.style.ImagePickerTheme)
  .start(RC_CODE)
```

With theme that extend `ef_BaseTheme`

For more example please kindly see the sample app. Thank you 😄

**Comment by kozmabalazs** [comment]
Thank you for help :)
