### ISSUE TITLE
image file could not be created

### ISSUE THREAD

**Issue by enes08** [esafirm/android-image-picker#337]
I just want to take a picture from the camera
   m use this mettotd cameraOnly().
  error message appears."image file could not be created"

## Specifications

  - Image Picker Version:2.4.3
  - Android OS:8.1.1
  - Phone:redmi 5 plus

  - Image Picker Version:2.4.3
  - Android OS:9
  - Phone:honor 9 lite

**Comment by Divasik** [comment]
Faced same issue, it seems the problem is in default isSaveImage (false) of camerOnly config. DefaultCameraModule.getCameraIntent() returns null and toast appears.

As a workaround extended ImagePickerCameraOnly, getIntent() with fixed config.

**Comment by Nightfright** [comment]
Have you tried adding saveImage to your ImagePicker.create(this).saveImage(true).start() line
seems like if you use android 10+ (>= api29) and you dont have saveImage(true) you will run into this problem.

**Comment by esafirm** [comment]
Please reopen if this still reproducible in 3.x
