### ISSUE TITLE
Unselect all images

### ISSUE THREAD

**Issue by dilip786** [esafirm/android-image-picker#339]
How can we handle all images unselected case, I mean i unselected all images and clicked on back button
Want to show a different UI if user unselected all images.

**Comment by esafirm** [comment]
Currently, this is only possible if you implement [custom UI](https://github.com/esafirm/android-image-picker/blob/main/sample/src/main/java/com/esafirm/sample/CustomUIActivity.kt) for image picker, or if you want to treat `Activity.RESULT_CANCEL` as unselect all signal

Other than that, we have to make **done** button show/hide logic customizable from config. Do you have any other suggestions?

**Comment by dilip786** [comment]
Other than that, we have to make done button show/hide logic customisable from config? is this possible, If yes can you please post code snippet
