### ISSUE TITLE
Write External permissions are ignored when targeting android R

### ISSUE THREAD

**Issue by JenyaKirmiza** [esafirm/android-image-picker#341]
## Steps to Reproduce the Problem
Set target ,compile sdk version to 30

![Screenshot_1615642458](https://user-images.githubusercontent.com/1162251/111031756-c5a27180-8411-11eb-9f7b-2b9865add7bf.png)

  1.

## Specifications

  - Image Picker Version: 2.4.0
  - Android OS: R(sdk 30) 
  - Phone: Pixel 2

**Comment by sinhpn92** [comment]
Why did this issues has closed?
I have used version 2.4.5 and I'm facing this issue.

**Comment by JenyaKirmiza** [comment]
@sinhpn92 yes you are right, i didn't have time to describe the issue correctly so i closed it.

**Comment by JenyaKirmiza** [comment]
@sinhpn92 can you provide your experience also here below in comments. It's serious because in summer we would have to target 30 sdk

**Comment by JenyaKirmiza** [comment]
@neonwarge04 Currently my fix is a bit messy, I didn't have time to make a good pr, so I've implemented it by myself integrating the lib inside my app. I've removed write external storage usage for android 10 and above and also made some changes in code to make it work.

**Comment by esafirm** [comment]
This should be fixed by #362
