### ISSUE TITLE
image not appear and can't take photo by camera

### ISSUE THREAD

**Issue by MinJerry1129** [esafirm/android-image-picker#345]
## Expected Behavior
I want get image form gallery.

## Actual Behavior
Image not appear and can't take photo.

## Steps to Reproduce the Problem
![Screenshot_12](https://user-images.githubusercontent.com/57364303/111141712-d3e1c080-85be-11eb-88c3-f860beac7615.png)
![Screenshot_13](https://user-images.githubusercontent.com/57364303/111141719-d5ab8400-85be-11eb-95de-b9b512e1a903.png)

## Specifications

  - Image Picker Version:1.13.0 & 2.0
  - Android OS: android 10 
  - Phone: Huawei p30 pro

**Comment by esafirm** [comment]
Can you try this on 2.4.5 or 3.0.0-alpha1 ?

**Comment by metinvio** [comment]
Same problem here. Have you been able to solve this?

**Comment by esafirm** [comment]
@metinvio is it exist in 3.0.0?

**Comment by metinvio** [comment]
@esafirm I updated to 2.4.5 now it works. Thank you a lot :) I think you can close the issue

**Comment by MinJerry1129** [comment]
Thanks.
