### ISSUE TITLE
image picker not working in navigation graph fragments

### ISSUE THREAD

**Issue by harpreetayali** [esafirm/android-image-picker#346]
## Expected Behavior
It should open using new method of registerImagePicker

## Actual Behavior
But when I initialize the registerImagePicker it gives exception of Fragment not attached to context may this exception comes because i am using navigation component.

## Steps to Reproduce the Problem
1. Link fragments using navigation component.
2. Then register image picker in fragment.

## Specifications

  - Image Picker Version: 3.0.0-alpha1
  - Android OS: 9
  - Phone:MI Note 5 Pro

**Comment by anupdey99** [comment]
Same issue but without navigation component

Image Picker Version: 3.0.0-beta-1
Android OS: 11

**Comment by esafirm** [comment]
Duplicated with https://github.com/esafirm/android-image-picker/issues/356
Will closing this one. Thanks for the report

**Comment by ljcleyba** [comment]
Still occurs on Android OS: 10, Image Picker Version: 3.0.0-beta-1.
Same issue but without navigation component.
