### ISSUE TITLE
Library doesn't pull into app

### ISSUE THREAD

**Issue by alfietapping** [esafirm/android-image-picker#349]
## Actual Behavior
Using Android Canary 10. Added maven + dependencies as detailed but no library shows when trying to access image picker in fragment

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Image Picker Version: 2.4.5
  - Android OS:
  - Phone:

**Comment by esafirm** [comment]
Probably a wrong configuration, please send the configuration and the build log of `./gradlew :app:help`
Could be jitpack is also down at that time. Closing this for now
