### ISSUE TITLE
I can't get the 3.0.0-beta1 from jitpack, but 2.4.5 works

### ISSUE THREAD

**Issue by JenyaKirmiza** [esafirm/android-image-picker#355]
## Actual Behavior
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find com.github.esafirm.android-image-picker:imagepicker:3.0.0-beta1.
     Required by:
         project :app

## Steps to Reproduce the Problem

`implementation "com.github.esafirm.android-image-picker:imagepicker:3.0.0-beta1"`
in your gradle app file

**Comment by coldfish** [comment]
Please check it:

https://github.com/esafirm/android-image-picker/issues/348#issuecomment-821970448

**Comment by WigerCheng** [comment]
implementation 'com.github.esafirm:android-image-picker:3.0.0-beta1'.

**Comment by esafirm** [comment]
Duplicate of https://github.com/esafirm/android-image-picker/issues/348
