### ISSUE TITLE
Fragment not attached to a context

### ISSUE THREAD

**Issue by anupdey99** [esafirm/android-image-picker#356]
## Expected Behavior
Should open imager picker from fragment

## Actual Behavior
Fragment h{9e363cc} (782f797a-94b7-4939-b68b-a5a1b80e4374) not attached to a context.
App crashed

## Steps to Reproduce the Problem

  1. register lister in a fragment
  val launcher = registerImagePicker { imageList: List<Image> -> }
  2. navigate to the fragment (not using nav component here)
 

## Specifications

  - Image Picker Version: 3.0.0-beta1
  - Android OS: 10/11
  - Phone: mi Note 7 pro

**Comment by pesjak** [comment]
Same problem. Navigation from fragment to fragment and then immediate crash.
`androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.ui.images.fragment: calling Fragment constructor caused an exception`

and   (415e9f03-c85b-432f-86d3-c007690ba0c9) not attached to a context.

**Comment by anupdey99** [comment]
Any luck with the issue?. In Android OS: 11 Camera only also does not work. App crash after taking picture.
My deal line is close.

**Comment by anupdey99** [comment]
For temp solution I am using method in fragment

val intent = createImagePickerIntent(requireContext(), config)
startActivityForResult(intent, IpCons.RC_IMAGE_PICKER)


override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        Log.d("debugImagePicker","imagePicker $requestCode $resultCode")
        if (resultCode == Activity.RESULT_OK && requestCode == IpCons.RC_IMAGE_PICKER && data != null) {
            val imageList = ImagePicker.getImages(data) ?: emptyList()
            if (imageList.isNotEmpty()) {
                val pathList = imageList.map { it.path }
                Log.d("debugImagePicker", "pathList $pathList")
            }
            return
        }
        super.onActivityResult(requestCode, resultCode, data)
    }

**Comment by audiserg** [comment]
private val launcher = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
        when (result.resultCode) {
            Activity.RESULT_OK -> {
                .....
            }
        }
    }
.......
   launcher.launch(createImagePickerIntent(requireContext(), getImagePickerConfig()))

**Comment by esafirm** [comment]
This should be fixed

**Comment by leesgit** [comment]
temporary use to this code

private val launcher = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) {
        val images = ImagePicker.getImages(it.data) ?: emptyList()
        val firstImage = images.firstOrNull()

        firstImage?.uri.let { uri->
            Glide.with(binding.yourImageView)
                .load(uri)
                .into(binding.yourImageView)
        }
    }

launcher.launch(createImagePickerIntent(requireContext(), ImagePickerConfig {your config))

**Comment by kldMohammed** [comment]
Any solution for this problem?

**Comment by kldMohammed** [comment]
> temporary use this code
> 
> ```
> private val launcher = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) {
>         val images = ImagePicker.getImages(it.data) ?: emptyList()
>         val firstImage = images.firstOrNull()
> 
>         firstImage?.uri.let { uri->
>             Glide.with(binding.yourImageView)
>                 .load(uri)
>                 .into(binding.yourImageView)
>         }
>     }
> ```
> 
> ```
> //when launch
> launcher.launch(createImagePickerIntent(requireContext(), ImagePickerConfig {your config))
> ```

I tried also same exceptions

**Comment by VictorAlbertos** [comment]
Declare a top level `lateinit` reference to the `ImagePickerLauncher`, and then initialise it during the `onAttach` callback `Fragment`.

```kotlin
class SignUpFragment : Fragment() {
    private lateinit var imagePickerLauncher: ImagePickerLauncher
    
    override fun onAttach(context: Context) {
        super.onAttach(context)
        imagePickerLauncher = registerImagePicker {
            
        }
    }
}
```
