### ISSUE TITLE
RuntimeException when MediaMetadataRetriever setDataSource occur some devices

### ISSUE THREAD

**Issue by tiny2021** [esafirm/android-image-picker#357]
## Actual Behavior
I have this issue when pick image. How to fix this please?
> android.media.MediaMetadataRetriever.setDataSource (MediaMetadataRetriever.java)
> android.media.MediaMetadataRetriever.setDataSource (MediaMetadataRetriever.java:321)
> android.media.MediaMetadataRetriever.setDataSource (MediaMetadataRetriever.java:369)
> com.esafirm.imagepicker.helper.ImagePickerUtils.getVideoDurationLabel (ImagePickerUtils.java:21)

## Specifications

  - Image Picker Version: 3.0.0-beta1
  - Android OS: 11
  - Phone: Galaxy S10+

**Comment by esafirm** [comment]
Hi, @tiny2021 could you please attach the complete stack trace for the issue? Is it crashing or is it something else? Thanks

**Comment by tiny2021** [comment]
Here is it. I think need to handle try catch for this
> Fatal Exception: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
>        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java)
>        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:321)
>        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:369)
>        at com.esafirm.imagepicker.helper.ImagePickerUtils.getVideoDurationLabel(ImagePickerUtils.java:21)
>        at com.esafirm.imagepicker.adapter.ImagePickerAdapter.onBindViewHolder(ImagePickerAdapter.java:21)
>        at com.esafirm.imagepicker.adapter.ImagePickerAdapter.onBindViewHolder(ImagePickerAdapter.java:21)
>        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:86)
>        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:86)
>        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:86)
>        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3)
>        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:3)
>        at androidx.recyclerview.widget.GridLayoutManager.t1(GridLayoutManager.java:94)
>        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:2)
>        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:20)
>        at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:7)
>        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:38)
>        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:37)
>        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
>        at android.view.View.layout(View.java:24475)
>        at android.view.ViewGroup.layout(ViewGroup.java:7383)
>        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
>        at android.view.View.layout(View.java:24475)
>        at android.view.ViewGroup.layout(ViewGroup.java:7383)
>        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
>        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
>        at android.view.View.layout(View.java:24475)
>        at android.view.ViewGroup.layout(ViewGroup.java:7383)
>        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
>        at android.view.View.layout(View.java:24475)
>        at android.view.ViewGroup.layout(ViewGroup.java:7383)
>        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
>        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
>        at android.view.View.layout(View.java:24475)
>        at android.view.ViewGroup.layout(ViewGroup.java:7383)
>        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
>        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
>        at android.view.View.layout(View.java:24475)
>        at android.view.ViewGroup.layout(ViewGroup.java:7383)
>        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
>        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
>        at android.view.View.layout(View.java:24475)
>        at android.view.ViewGroup.layout(ViewGroup.java:7383)
>        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
>        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
>        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
>        at android.view.View.layout(View.java:24475)
>        at android.view.ViewGroup.layout(ViewGroup.java:7383)
>        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
>        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
>        at com.android.internal.policy.DecorView.onLayout(DecorView.java:1225)
>        at android.view.View.layout(View.java:24475)
>        at android.view.ViewGroup.layout(ViewGroup.java:7383)
>        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4260)
>        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3695)
>        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
>        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9965)
>        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
>        at android.view.Choreographer.doCallbacks(Choreographer.java:809)
>        at android.view.Choreographer.doFrame(Choreographer.java:744)
>        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
>        at android.os.Handler.handleCallback(Handler.java:938)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at android.os.Looper.loop(Looper.java:246)
>        at android.app.ActivityThread.main(ActivityThread.java:8506)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
