### ISSUE TITLE
Empty images list when project integrate with Instabug

### ISSUE THREAD

**Issue by nthieu90** [esafirm/android-image-picker#358]
## Expected Behavior
After granted storage permission, it should display images list

## Actual Behavior
An empty image list with a snackbar  has empty message, only Ok button

## Steps to Reproduce the Problem

  1. Integrate with Instabug 10.5.0
  2. Open ImagePicker
  3. Granted storage permission

## Specifications

  - Image Picker Version:  3.3.0..0-beta1
  - Android OS: 11
  - Phone: Samsung S21

**Comment by xpdlf1004** [comment]
This is related to https://github.com/esafirm/android-image-picker/pull/362.

This library checks whether "write permission" is granted or not,  but the "write permission" is ignored in Android 11.

**Comment by esafirm** [comment]
Fixed in https://github.com/esafirm/android-image-picker/pull/431
