### ISSUE TITLE
Is there a way to change language for "selected" and "DONE"?

### ISSUE THREAD

**Issue by SupreeSeekSter** [esafirm/android-image-picker#36]
How can I change the language of these two words?

<img width="403" alt="screen shot 2560-03-19 at 23 48 10" src="https://cloud.githubusercontent.com/assets/19761196/24082877/22c1b1f2-0cff-11e7-93e8-09e6cce0ad07.png">

**Comment by Rainer-Lang** [comment]
@SupreeSeekSter Try to override ```<string name="ef_done">DONE</string>``` and ```<string name="ef_selected">%d selected</string>``` in your ```strings.xml```.

**Comment by esafirm** [comment]
Currently this is the best solution. Closing for now
