### ISSUE TITLE
Crash: Can't create sort clause without columns

### ISSUE THREAD

**Issue by A7madSaber** [esafirm/android-image-picker#367]
## Expected Behavior
Open image picker view

## Actual Behavior
Crash 
    java.lang.IllegalArgumentException: Can't create sort clause without columns.

## Steps to Reproduce the Problem

  1. Open image picker from fragment with ImagePickerConfig 

## Specifications

  - Image Picker Version: 3.0.0-beta4
  - Android OS: 29
  - Phone: Oppo F7

**Comment by strmchsr** [comment]
it still not included in latest release @esafirm
