### ISSUE TITLE
Android SDK 30 and Manage External Storage Permission

### ISSUE THREAD

**Issue by Prog-MohamedAbdelnaser** [esafirm/android-image-picker#371]
https://support.google.com/googleplay/android-developer/answer/10467955

**Comment by esafirm** [comment]
Hi @Prog-MohamedAbdelnaser what's the issue here?
AFAIK AIP doesn't use `MANAGE_EXTERNAL_STORAGE` permission

**Comment by AnandRH** [comment]
@esafirm Issue here is  with Android 11 and targetSDK to 30.
Storage premission  is removed .We might need to use MANAGE_EXTERNAL_STORAGE permission to get the photos.

**Comment by esafirm** [comment]
https://github.com/esafirm/android-image-picker/pull/362 should fix the issue right? Or is it a different thing?
