### ISSUE TITLE
Exclude Specific File Types

### ISSUE THREAD

**Issue by mikemike396** [esafirm/android-image-picker#372]
Curious if there is a way to exclude certain file extensions? Specifically if I allow users to select videos I am looking to only allow .mp4 (video/mp4) formats. I see this https://github.com/esafirm/android-image-picker/pull/100 but this seems to be related to specific files not a whole extension type.

Thanks!

**Comment by esafirm** [comment]
Hi @mikemike396 , currently this is only possible through [custom components](https://github.com/esafirm/android-image-picker/blob/master/docs/custom_components.md). You can replace the `ImageFileLoader` to be precise
