### ISSUE TITLE
Camera folder showing empty images 

### ISSUE THREAD

**Issue by DucMinh2412** [esafirm/android-image-picker#391]
This bug is still not fixed on current devices
  - Image Picker Version: 2.4.5
  - Android OS: 10
  - Phone: All phone

**Comment by asknask** [comment]
@DucMinh2412 I don't have a solution for you but version 2.3.2 of this library doesn't have this problem.

**Comment by esafirm** [comment]
For 2.x please raise a PR. Otherwise, you can check in version 3.x and raise the issue again.
