### ISSUE TITLE
No Images Found on Api 30

### ISSUE THREAD

**Issue by shafayatb** [esafirm/android-image-picker#392]
Getting no images found on Api 30  Android Q. Using version 3.0.0-beta4.

![Screenshot_1636133799](https://user-images.githubusercontent.com/20676587/140554283-e71c768e-4fe4-40b5-b70b-02f86f87684e.png)

**Comment by esafirm** [comment]
This should be fixed in the latest `3.0.0`. Please reopen if the issue still persists.
