### ISSUE TITLE
Is there a way to change language for "selected" ?

### ISSUE THREAD

**Issue by laisuki1109** [esafirm/android-image-picker#397]
image Picker version: 3.0.0-beta
![big-Screenshot_20211111-133246_LearnHour](https://user-images.githubusercontent.com/43807081/143563397-6a9cdf43-b105-4f3b-92f0-f1238d3ebd98.jpeg)
1

**Comment by tungthanh1497** [comment]
Did you try to override string with key "ef_selected_with_limit" in your application's strings.xml

```
Example:
<string name="ef_selected_with_limit" tools:override="true">%1$d/%2$d selected</string>
```

**Comment by esafirm** [comment]
Closing the issue as the current solution for this is to override the string itself like https://github.com/esafirm/android-image-picker/issues/397#issuecomment-1006316520
