### ISSUE TITLE
Api 31 resolveActivity

### ISSUE THREAD

**Issue by SirChegal** [esafirm/android-image-picker#399]
intent.resolveActivity always null on devices running Android 11 
CameraHelper cannot start the camera and reports an error  ef_error_no_camera
android.permission.QUERY_ALL_PACKAGES

**Comment by bierzorutas** [comment]
Same problem seen here

**Comment by esafirm** [comment]
Will probably check.

What's the steps to reproduce this?

**Comment by esafirm** [comment]
Not reproducible. Closing this
