### ISSUE TITLE
Missing default (english) translation for camera permission

### ISSUE THREAD

**Issue by alessandrotedd** [esafirm/android-image-picker#405]
## Expected Behavior
App shows English text when asking for camera permissions

## Actual Behavior
App shows text in Indonesian
<img width="269" alt="image" src="https://user-images.githubusercontent.com/43759103/193909070-2d4664e0-41e3-4cd8-8b82-d5c71b8d74a1.png">

## Steps to Reproduce the Problem
I found this issue when compiling with Android SDK 33
  1. use compileSdk 33 and targetSdk 33 in build.gradle
  2. run app
  3. click "Pick image"
  4. snackbar shows text in Indonesian instead of English

## Specifications

  - Image Picker Version: 3.0.0
  - Android OS: API 33
  - Phone: Emulator (SDK 33)

**Comment by esafirm** [comment]
Fixed in https://github.com/esafirm/android-image-picker/issues/405
