### ISSUE TITLE
Not working on android 13

### ISSUE THREAD

**Issue by kei2213** [esafirm/android-image-picker#422]
## Steps to Reproduce the Problem

  1. Open Image Picker

## Specifications

  - Image Picker Version: 2.4.5
  - Android OS: Android 13 - APi 33
  - Phone: Samsung Galaxy S22
![Screenshot_20221106_165628_TRAN MINH BDS](https://user-images.githubusercontent.com/51433748/200164546-adbe7613-437a-43b7-b469-41c0a6fdba63.jpg)

**Comment by esafirm** [comment]
Can you check version `3.0.0` Thansk ?

**Comment by longquangpham90** [comment]
> Can you check version `3.0.0` Thansk ?

We checked version 3.0.0, but its the same, lib can not accept permission
