### ISSUE TITLE
Issue with Android 33 and above

### ISSUE THREAD

**Issue by hzqabdullah** [esafirm/android-image-picker#442]
## Expected Behavior
- Should be able to display all the images from the phone.
- Should be able to open the camera.

## Actual Behavior
- Doesn't display the images when the library is open.
- Cannot open the camera when clicked on camera icon.

<img width="316" alt="Screenshot 2023-06-09 at 2 38 46 PM" src="https://github.com/esafirm/android-image-picker/assets/33567180/0b5917d1-0c5c-4a19-9ea5-85f3d439a6bb">

## Steps to Reproduce the Problem

  1. Open the library in Android 33 and above.
  2. The library is not displaying the images in the album.
  3. When clicked on the camera icon, the app doesn't open the camera.
  4. Already allowed the permission for photo in app permission settings.

## Specifications

  - Image Picker Version: 2.4.5
  - Android OS: Android 13
  - Phone: Samsung Galaxy M33 5G

**Comment by IlyaSibogatov** [comment]
@hzqabdullah Find a solution?

**Comment by hzqabdullah** [comment]
Nope

**Comment by JEuler** [comment]
Have you tried with 3.0.0 version?

**Comment by justColbs** [comment]
Same issue here on 2.4.5. I can't use 3.0.0 because I get the following error when running: 

Could not resolve com.github.esafirm.android-image-picker:imagepicker:3.0.0.
