### ISSUE TITLE
Bugs to SnackBarView

### ISSUE THREAD

**Issue by xpdlf1004** [esafirm/android-image-picker#47]
If permission denied and user choose 'Nerver Ask Again', show snackbar with an action that navigate to app settings

But snackbar view does not appear because of the wrong order between initialization of snackbar view and checking permission on creating activity.

This method have to call before permission check (onResume).
```
ViewUtils.onPreDraw(snackBarView, new Runnable() {
    @Override
    public void run() {
        snackBarView.hide();
    }
});
```
Thie initializing call "snackBarView.hide()" is hiding the snackbar which is already shown.

**Comment by Rainer-Lang** [comment]
@xpdlf1004 Could you make a PR?

**Comment by xpdlf1004** [comment]
@Rainer-Lang OK~!
