### ISSUE TITLE
Is the pic taken from the camera after I dismiss it deleted?

### ISSUE THREAD

**Issue by Rainer-Lang** [esafirm/android-image-picker#5]

**Comment by esafirm** [comment]
No it's not, it's required to behave like that because if you're not set `refurnAfterCapture` to`true`, it will show your image that you just captured in the gallery

**Comment by Rainer-Lang** [comment]
Is it possible to make this configurable? I really would need it.

**Comment by esafirm** [comment]
The library itself returning `Image` object that have a `path` to the file. You can just delete it from there.
