### ISSUE TITLE
Failed to resolve 

### ISSUE THREAD

**Issue by sandeshlasnapure** [esafirm/android-image-picker#51]
`Error:(47, 13) Failed to resolve: com.github.esafirm.android-image-picker:imagepicker:1.7.2@aar`

**Comment by esafirm** [comment]
Sorry wrong tag naming. Please try again.

**Comment by HammadNasir** [comment]
I'm facing the same issue.

**Comment by esafirm** [comment]
@HammadNasir don't use `aar` suffix anymore
