### ISSUE TITLE
Image storing issue

### ISSUE THREAD

**Issue by kozmabalazs** [esafirm/android-image-picker#53]
Hello @esafirm,
 
When I use the image picker to take a new picture, the image is saved in both default camera folder and the folder I specified through .imageDirectory("name") method. 

Is there a way to have only one copy of the file?

Thank you.

**Comment by esafirm** [comment]
@kozmabalazs can you just delete it after you use the image?

**Comment by esafirm** [comment]
@kozmabalazs close it for now
