### ISSUE TITLE
What about saving selected images in my own folder?

### ISSUE THREAD

**Issue by hadalaba** [esafirm/android-image-picker#54]
Cause I don't want to lose them, if user decides to delete them from gallery on phone.
P.S. In my app I'm saving the uri of images into db

**Comment by esafirm** [comment]
@hadalaba you can copy it to you own folder. It is outside what this library should do.

**Comment by hadalaba** [comment]
hmm, then what do you think about adding the type of selected images? GALLERY, PHOTO or something like that

**Comment by hadalaba** [comment]
Isn't id of captured photo is always a zero?

Sorry for questions like that :)

**Comment by hadalaba** [comment]
After all manipulations, I noticed that folders are recreated and added to existing ones after function onResume in  ImagePicker activity.
And  my copied files don't displayed in ImagePicker activity (they saved in custom folder, which created by .imageDirectory("Custom name")) . But original files are displayed.
Also Activity can't find pictures in Download directory.

P.S. feeling myself so awkward after these massages 😣

**Comment by esafirm** [comment]
It's fine, feel free to open new issues anytime 😄 

> hmm, then what do you think about adding the type of selected images? GALLERY, PHOTO or something like that
Hmm what's your use case with this? 

> Isn't id of captured photo is always a zero?
What id? 

All images in `ImagePickerActivity` is from `MediaStore`, so if your image is included/registered in `MediaStore`, it would show in `ImagePickerActivity`
