### ISSUE TITLE
Is there a way to edit the xml layout of the Image picker activity

### ISSUE THREAD

**Issue by AnthonyEd** [esafirm/android-image-picker#55]
It's because I want to add a little top padding to the toolbar, the window tansculent status is set to true and therefore drags the toolbar to the status bar so please how can I edit the Image picker xml layout?

**Comment by esafirm** [comment]
@AnthonyEd maybe overriding the xml, haven't tried it myself.

**Comment by esafirm** [comment]
Closing for now due inactivity
