### ISSUE TITLE
Can not move to previous screen

### ISSUE THREAD

**Issue by pavecho** [esafirm/android-image-picker#56]
I pressed the back button at folderMode(false).
It will not go back to the previous screen.

ImagePicker.create(this)
                .returnAfterFirst(true) 
                .folderMode(false) 
                .multi() 
                .limit(10) 
                .showCamera(false)
                .enableLog(false) 
                .start(PICK_IMAGE_MULTIPLE);

**Comment by dmmajithia** [comment]
I'm having the same problem!
Is this because I'm testing it on the emulator?

**Comment by AnthonyEd** [comment]
I have the same problem, I even tested it on a real phone still the same.

**Comment by mihudevcom** [comment]
The issue is in ImagePickerActivity:

` @Override
    public void onBackPressed() {
        if (!recyclerViewManager.isDisplayingFolderView()) {
            setFolderAdapter(null);
            return;
        }
        setResult(RESULT_CANCELED);
        super.onBackPressed();
    }`

I can take care of it this week if the owner lets me. What do you think @esafirm ?

**Comment by esafirm** [comment]
@mihudevcom please do! 🙏

**Comment by yarodevuci** [comment]
@mihudevcom what is recyclerViewManager

**Comment by mihudevcom** [comment]
@yarodevuci Not 100% sure yet since i didn't go into details. I just took a fast look and since the bug is related to the back button and you can't go back than it's very possible that in the onBackPressed is the problem.

**Comment by yarodevuci** [comment]
I did this .returnAfterFirst(false), fixed my problem @mihudevcom

**Comment by mihudevcom** [comment]
@yarodevuci I'm using 1.7.2 with that option on and still have the problem. What version are you using?

**Comment by yarodevuci** [comment]
@mihudevcom same latest version

**Comment by mihudevcom** [comment]
@pavecho @AnthonyEd @dmmajithia What versions are you guys using?

**Comment by esafirm** [comment]
@mihudevcom it's definitely in `onBackPressed` 
Would you mind if i trying solve this problem today instead? Thanks

**Comment by mihudevcom** [comment]
@esafirm Of course not. Go ahead. :)

**Comment by esafirm** [comment]
@mihudevcom @pavecho @dmmajithia @AnthonyEd 
Can anyone confirm the fix?  it's in
```
com.github.esafirm.android-image-picker:imagepicker:1.7.3-beta-1
```

Cheers!

**Comment by pavecho** [comment]
It was fixed! Thanks @esafirm

**Comment by esafirm** [comment]
@pavecho You're welcome
Promoted to release 🎉
https://github.com/esafirm/android-image-picker/releases/tag/1.7.3
