### ISSUE TITLE
java.lang.IllegalStateException: return after first only usable with MODE_SINGLE

### ISSUE THREAD

**Issue by mikemasam** [esafirm/android-image-picker#61]
java.lang.IllegalStateException: return after first only usable with MODE_SINGLE

>     public static ImagePicker getImagePicker(Activity context, ArrayList<Image> images,int max){
        return  ImagePicker.create(context)
                .returnAfterFirst(true) // set whether pick or camera action should return immediate result or not. For pick image only work on single mode
                //.folderMode(true) // folder mode (false by default)
                //.folderTitle("Folder") // folder selection title
                //.imageTitle("Tap to select") // image selection title
                //.single() // single mode
                .multi() // multi mode (default mode)
                .limit(max) // max images can be selected (99 by default)
                //.showCamera(true) // show camera or not (true by default)
                //.imageDirectory("Camera") // directory name for captured image  ("Camera" folder by default)
                .origin(images) // original selected images, used in multi mode
                //.theme(R.style.CustomImagePickerTheme) // must inherit ef_BaseTheme. please refer to sample
                .enableLog(false); // disabling log
                //.imageLoader(new GrayscaleImageLoder()) // custom image loader, must be serializeable

    }

**Comment by esafirm** [comment]
@mikemasam this is intended, because you can't have MULTI_MODE functionality if you chose `returnAfterFirst` = true

**Comment by mikemasam** [comment]
thanks,
