### ISSUE TITLE
can't back when not using folder mode

### ISSUE THREAD

**Issue by cahyasetya** [esafirm/android-image-picker#63]
i'm sorry sir, i can't back to my previous activity when i'm not using folder mode. does when i'm not using folder mode and back pressed from image section it will be directed to folder section?
i'm sorry for my bad english

**Comment by esafirm** [comment]
@cahyasetya what version are you using? 

You can speak to me with bahasa 😁 but i think other people will be confused.

**Comment by cahyasetya** [comment]
i'm sorry. it seems i'm using the outdated version because i'm not the one who add the dependency. thanks for your response. keep moving forward sir 😄

**Comment by esafirm** [comment]
@cahyasetya no problem. Cheers!
