### ISSUE TITLE
[feature] Custom Image Sources

### ISSUE THREAD

**Issue by chpasha** [esafirm/android-image-picker#67]
Hello,

want to thank you first for your wonderful small lib. I have a feature request that might be useful for other users. What do you think about introducing a custom source concept for the images? The changes that are needed I quite trivial: 
- rename ImageFileLoader to DeviceMediaSource (may be you can pick a better name, but hopefully you've got the idea)
- extract an ImageSource interface from it with two methods: loadImages(boolean isFolderMode,ImageLoaderListener listener) and abortLoadImages()
- introduce new configuration option and builder method (like imageSource) and use it's value as parameter for ImagePickerPresenter (of course with DeviceMediaSource as fallback if it is not set)

that is actually it. I tried these changes on a local copy as proove-of-concept and it works like a charm. With this change it becomes possible to select images from some custom sources which are not available to media scanner (like external app dirs) or even some internet resources (if somebody ever needs a functionality like these).

**Comment by esafirm** [comment]
@chpasha 

Hello, and thank you for using this lib, glad i could help.

I actually been thinking about this. How the implementation for passing the source class to `ImagePickerActivity`? 

Currently a custom `ImageLoader` use `Serializeable` but i think about a `Singleton` that as a source for `ImagePickerActivity` 

WDYT?

**Comment by chpasha** [comment]
yes, for now I have to pass serializable ImageSources (like Loaders) which is a bit awkward but I had to make changes quickly, so making class Serializable was not a problem. Not sure what would be a better solution, I think serilizables are better than singletons

**Comment by esafirm** [comment]
With [custom component](https://github.com/esafirm/android-image-picker/blob/master/docs/custom_components.md) already added to the lib, we can have custom image source.
