### ISSUE TITLE
Update to Glide v4?

### ISSUE THREAD

**Issue by Rainer-Lang** [esafirm/android-image-picker#68]

**Comment by esafirm** [comment]
Can you tell me a brief pros n cons? Or just a link 😄

**Comment by Rainer-Lang** [comment]
I would suggest to read the release changelog: https://github.com/bumptech/glide/releases
And at my point - the changes a dev has to make in code are very small.

**Comment by esafirm** [comment]
@Rainer-Lang will check on it ASAP 😄 👍

**Comment by ks419** [comment]
Please do it asap. Adding glide externally breaks compatibility.

**Comment by esafirm** [comment]
@Rainer-Lang @ks419 updated and release in `1.9.0` 🎉
Please kindly check 🙏
