### ISSUE TITLE
Title should be always showed as long is nothing is selected

### ISSUE THREAD

**Issue by chpasha** [esafirm/android-image-picker#70]
This is a very minor change that I find rather useful - I think it makes more sense to always show the title as long as nothing is selected (and only after that show "1 / X selected"). For now if we choose multiple select mode without folders, title is never shown (which is actually an unexpected behavior for developer, since we set the title but never see it) - it took me a couple of minutes to understand where is my title suddenly gone until I remembered that the only thing I've changed was multiple selection. Title is a brief explanation for user about what he is supposed to do now (for instance what are these pictures are about or where do they come from) so I think it is crucial to show it for the first time the user sees image picker activity.

The change is trivial - modify getTitle method inside RecyclerViewManager to this
```
int selectedImagesCount = imageAdapter.getSelectedImages().size();
 if (config.getMode() == ImagePicker.MODE_MULTIPLE && selectedImagesCount > 0)
 {
            return config.getLimit() == ImagePicker.MAX_LIMIT
                    ? String.format(context.getString(R.string.ef_selected), selectedImagesCount)
                    : String.format(context.getString(R.string.ef_selected_with_limit), selectedImagesCount, config.getLimit());
}
```

**Comment by esafirm** [comment]
@chpasha fair enough. I take some different implementation though. For making this behavior optional, you have to set your `imageTitle` explicitly. 

ex: 
```java
ImagePicker.create(this).imageTitle("Tap to select").start(CODE);
```

Unless you set it, the behavior still the same as previous version. 

PS: This introduce some breaking changes too in how the default title is obtained. (maybe affecting your code)

Cheers!

**Comment by esafirm** [comment]
Released @ https://github.com/esafirm/android-image-picker/releases/tag/1.8.0
