### ISSUE TITLE
Default config is invalid

### ISSUE THREAD

**Issue by jasennett** [esafirm/android-image-picker#71]
The default config created by `ImagePickerConfigFactory` creates a config with mode set to multi, and "return after first" set to true, which is invalid according to `ConfigUtils.checkConfig()`

**Comment by esafirm** [comment]
@jasennett will fix it ASAP

**Comment by esafirm** [comment]
@jasennett fixed in `1.9.0` please kindly check 🙏

**Comment by jasennett** [comment]
Yep, works great, thanks for the fix!
