### ISSUE TITLE
Getting Path From Uri?

### ISSUE THREAD

**Issue by GitUser4732** [esafirm/android-image-picker#74]
Hello,
I am using Aviary to edit a photo that was selected from picker. This returns a Uri in onActivityResult. How can I get the correct path from this Uri result to update my image with Image.setpath?
Thanks

**Comment by esafirm** [comment]
@GitUser4732 Did you want to update the `Image` object? 

I'm not familiar with Aviary result `Uri` could you please give me some `String` representation from that?

**Comment by GitUser4732** [comment]
Yes I want to update my `Image` objects path to be that of the edited image result.

The `Uri` result is `content://media/external/images/media/243255`.
I need help to get a result from this `Uri` like below.

`/storage/emulated/0/Pictures/aviary-image-1505709867315.jpeg`

**Comment by esafirm** [comment]
@GitUser4732 my best shot is using this function from `aFileChooser` 😄 

https://github.com/iPaulPro/aFileChooser/blob/master/aFileChooser/src/com/ipaulpro/afilechooser/utils/FileUtils.java#L257

Since this is not exactly library issues, i will close this one. Cheers!
