### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by youngsdeveloper** [esafirm/android-image-picker#76]
` java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.photoversusapp.app-2/split_lib_dependencies_apk.apk:classes40.dex)`

I have received this in my logcat when i try yo open the image picker. A couple of days ago this runs well.

**Comment by youngsdeveloper** [comment]
I have solved the problem!

I got the NoSuchMethodError because i added the Glide's library two times. When i removed Glade from my build.gradle, it worked again. I suppose that this library have glide already added.

**Comment by esafirm** [comment]
@youngsdeveloper is it a different version of Glide? 

I think it's related with this https://github.com/esafirm/android-image-picker/issues/75
