### ISSUE TITLE
Manifest error

### ISSUE THREAD

**Issue by bisfrim** [esafirm/android-image-picker#8]
I have an issue when i sync the library. "manifest merger failed with multiple errors". Any suggestions. Thanks

**Comment by esafirm** [comment]
@bisfrim what version did you use?

**Comment by bisfrim** [comment]
I used the latest version "1.2.3" and also tried the other previous versions 1.2.2 and 1.2.1, but still gets the same error. I'm using latest gradle. I've tried to lower my Min SDK from 16 to 14 but I still run into the same manifest error. Thanks.

**Comment by esafirm** [comment]
I think this have something to do with duplication/conflict in manifest file.

Can you please provide with the complete message/stacktrace. Thanks

**Comment by bisfrim** [comment]
I checked out the link you sent and its fixed now. Had to put this in my manifest tools:node="replace". Thank you

**Comment by esafirm** [comment]
@bisfrim You're welcome 😄

**Comment by aimanbaharum** [comment]
This happens when there is a conflict with library's manifest and the app's one. My solution was to remove my app's FileProvider path definition as it is already handled by the library.
