### ISSUE TITLE
Abstract Simplifier Class

### ISSUE THREAD

**Issue by vitorhugods** [esafirm/android-image-picker#82]
I truly believe the most of the uses if this Library are quite simple and straight-forward, so most of the java boiler-plate can be reduced by extending a class that already overrode the onActivityResult and received the image.

The developer could request an image by calling requestImage(), and receive it in an abstract method called onImagesResult(List<Image>). If the developer wants to personalize the selection, he could override a method called customizeImageSelectionParameters(ImagePicker,Builder params) in an Activity. Exemple of utilization:
```
class MyActivity extends ImagePickActivity{
    
    void onCreate(/**..
        ...
        ...
        **/
        myButon.setOnClickListener(/** call requestImages() **/
    }

    @Override //These parameteres are Single and return after first by default. Override is optional
    void customizeImageSelectionParameters(ImagePicker.Builder params){
        params.returnAfterFirst(false)
            .multi(true)
            .limit(10);
    }

    @Override //Obligatory override, get your images.
    void onImagesResult(List<Image> images){
        //todo Images selected by user
    }

}
```
I've created an "ImagePickActivity" and "ImagePickFragment" base classes myself, that uses this library and one that I've made to compress Images. My implementation receives the images onResult, compresses them and calls onImagesResult(). BUT, I've made it in Kotlin. It's simple anyways.

I can share with you and re-implement it in Java if it is an interesting feature to this library.

**Comment by esafirm** [comment]
@vitorhugods it certainly interesting but i have some question regarding extending the library `Activity` itself

1. In your use case, why not compressing it after you get the `Image` object from the library? 
2. Do you have other use cases where it make sense to extending the `Activity` 

Cheers!

**Comment by vitorhugods** [comment]
I'm indeed compressing it after getting the Image object. My class gets the file provided by the Image Object, compresses it, saves in the app cache folder, and then calls the "onImagesResult" method with the compressed reference.

About the use cases, simplification is the only one that I came across so far. When using the library in several activities I realized that some pieces of code were always the same. So this approach reduced copy/paste.

**Comment by esafirm** [comment]
Did we call the "custom" ImagePickerActivity with `Intent` API? 

TBH i don't want people to extend the `Activity` especially for a problem / use case that can be handled without extending. So i think this should not be in the library, at least for now.

**Comment by vitorhugods** [comment]
I considered the option of adding these Activity and Fragment because they are just tools. Users can choose wether to use it or not.
But I see your point, extending an Activity is an aggressive way to reduce copy/pasting.

**Comment by esafirm** [comment]
Will closing this issue for now. Thanks for your suggestion 👍
