### ISSUE TITLE
Failed to resolve the lib

### ISSUE THREAD

**Issue by clamentsanz** [esafirm/android-image-picker#83]
Hi,

When i try to add you lib using : 
`    compile 'com.github.esafirm.android-image-picker:imagepicker:1.8.0'
`

I have this error : 

> Failed to resolve: com.github.esafirm.android-image-picker:imagepicker:1.8.0 Show in File Show in Project Structure dialog

**Comment by esafirm** [comment]
@clamentsanz did you add the jitpack repo in your app module or in `allproject`?

```
allprojects {
    repositories {
        maven { url "https://jitpack.io" }
    }
}
```

**Comment by esafirm** [comment]
Closing this for now. Please feel free to reopen.
