### ISSUE TITLE
Viewfinder in camera

### ISSUE THREAD

**Issue by maxatcn** [esafirm/android-image-picker#84]
I have a requirement to take photo with a viewfinder. Means, when launching the camera, there is a rectangle or square area to pick up the image,  rather than the full screen image.   I read the doc and code a bit, but not a clear view on this so far.

I am not sure if viewfinder is the proper term to describe in this project.  Is there any way to fulfil my requirement in the current framework?   
Thanks for any comment.

**Comment by esafirm** [comment]
This library in not designed for custom camera interface. In fact it uses only `Intent` for camera. 
I think you should look at [this](https://github.com/Fotoapparat/Fotoapparat)
