### ISSUE TITLE
DefaulCameraModule Data on ActivityResult always Null

### ISSUE THREAD

**Issue by iqbalprabu** [esafirm/android-image-picker#85]
DefaulCameraModule Data on ActivityResult always Null
I use new version 1.9.0 and I've tried it also with the version below

can you help me ?

**Comment by esafirm** [comment]
1. Is it working on the previous version? 
2. What's your Android version?

**Comment by iqbalprabu** [comment]
1. isn't working
2. my Android version is 7.0

**Comment by esafirm** [comment]
@iqbalprabu will check on it on the weekend. Did you use default camera app?

**Comment by esafirm** [comment]
Hi @iqbalprabu @taskfriendinc. Unfortunately i can't reproduce this in the emulator for both case (In Nougat and Oreo).

Can either of you reproduce the issue with the sample app? If not, then i need to know your code. 

Cheers!

**Comment by taskfriendinc** [comment]
Hi @esafirm checking in your sample code only. In my case, working fine in Nougat. But have some problem with Oreo.

**Comment by esafirm** [comment]
Will closing this for now due inactivity and one of the issue is already solved. Please feel free to re-open it again.
