### ISSUE TITLE
Copied files not display in a custom directory

### ISSUE THREAD

**Issue by hadalaba** [esafirm/android-image-picker#89]
When I pick images from any folder and copy them into the custom directory [ImagePicker.imageDirectory(getString(R.string.app_name))], those images not displayed in my directory of PickerActivity
They appear only after opening Gallery app provided by device.

**Comment by esafirm** [comment]
@hadalaba well, the thing is we're using `MediaStore.Images.Media.EXTERNAL_CONTENT_URI` 
So to make sure your image is showed in the picker, you have to insert your image to Media Store.

Ref: https://stackoverflow.com/questions/8560501/android-save-image-into-gallery

It would be nice if we can automatically do the scanning, but i still need to do some research. 
But my concern with scanning all files is the speed of showing images in gallery.

**Comment by hadalaba** [comment]
The ref helped me, Thank You for wonderful library :)

**Comment by esafirm** [comment]
You're very welcome. Closing this ✔️
