### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by LinkOut** [esafirm/android-image-picker#9]
how can i translate "n/n selected" and "done"? 

Thanks

**Comment by esafirm** [comment]
Well, you can pull this repo, rename it, and use it in your project. 
Or you can always contribute the translation to this repo.

There's still no function to set it programmatically.

**Comment by LinkOut** [comment]
ok added italian and romanian translations #10 thanks :)

**Comment by esafirm** [comment]
@LinkOut https://github.com/esafirm/android-image-picker/pull/10 merged! Thanks!
