### ISSUE TITLE
Double click on image

### ISSUE THREAD

**Issue by hadalaba** [esafirm/android-image-picker#90]
If I clicking twice on an image (like double click), the selected count title in action bar gets bigger by 2 points. And for deselecting image I should click twice again. If i do this slowly everything normal and fine.
But I think for user it would a little disappointing, if he wants fast response from UI
P.S. I refactor layout of ImagePickerActivity (ef_activity_image_picker.xml) for Toolbar elevation
The question is, is it possible to fix the problem? Or is it a problem at all? XD

**Comment by hadalaba** [comment]
And speaking about responsive UI, is it possible in the near future add returnAfterFirst(true) in multi() choice mode?

**Comment by esafirm** [comment]
@hadalaba woops! will check on it.

> And speaking about responsive UI, is it possible in the near future add returnAfterFirst(true) in multi() choice mode?

How is it related to responsive UI? What is the use case when you need a multi pick with return after first?

**Comment by hadalaba** [comment]
`.returnAfterFirst(true) // set whether pick or camera action should return immediate result or not. For pick image only work on single mode`

In multi pick mode after camera action I need return result immediately. It would be cool if you'd added such an opportunity in the near future

**Comment by esafirm** [comment]
@hadalaba it seems that i can't reproduce the double tap issue. On the other note i added the elevation to the toolbar https://github.com/esafirm/android-image-picker/commit/5cb4fe1f3212ac0f1a861d7dfccf0492a88c90fd 😄 

`returnAfterFirst` is intended to affect the camera and gallery picker. What you want is rather a camera only `returnAfterFirst`. I think it's a good addition to have more customizable setting like that. 

I think changing `returnAfterFirst` type from `boolean` to finite `int` or `enum` will do the trick.

**Comment by hadalaba** [comment]
I'll patiently wait for that feature (`returnAfterFirst`) 👍

**Comment by esafirm** [comment]
@hadalaba added in [here]https://github.com/esafirm/android-image-picker/commit/266c88bfbb475eb0828a8e0d9259883fbd164dcf() 

`returnAfterFirst` now replaced by `returnMode` 

`ReturnMode` has 4 functions

 * NONE -> When image is picked, ImagePickerActivity will not dismissed even in Single Mode
 * ALL -> When image is picked dismiss then deliver result
 * CAMERA_ONLY -> When image is picked with Camera, dismiss then deliver the result
 * GALLERY_ONLY -> Same as CAMERA_ONLY but with Gallery

Just wait for the next release. Thanks for your patience
