### ISSUE TITLE
onActivityResult not gets called after selecting image from gallery

### ISSUE THREAD

**Issue by amankumarjain** [esafirm/android-image-picker#93]
1. onActivityResult not gets called after selecting image from gallery
2. cameraModule.getCameraIntent(mainActivity), in doc its incorrect

please provide some solution for 1st.

**Comment by esafirm** [comment]
@amankumarjain for question 1
1. what OS version you use? 
2. Is it an emulator or a real device? 
3. What camera app you use?

**Comment by esafirm** [comment]
Hi if you have a problem with `DefaultCameraModule` before please use the new camera-only api in 1.10.0

```
ImagePicker.cameraOnly().start(activity);
```

And i'm closing this one, please don't hesitate if you want to open it again.

**Comment by ikasapoglu** [comment]
I was troubling on the same issue. I'm calling ImagePicker from Fragment. So, changing  
 this
 ImagePicker.create(activity) //getactivity for java
to
ImagePicker.create(this@MyFragment)

solved issue.
