### ISSUE TITLE
Camera retunrn file in diffrent format

### ISSUE THREAD

**Issue by amankumarjain** [esafirm/android-image-picker#94]
camera return file path in this format:
file:/storage/emulated/0/Pictures/Camera/IMG_20171230_1523551629838020.jpg

**Comment by esafirm** [comment]
@amankumarjain CMIIW, the problem is the `file:/` part? Can you elaborate more?

**Comment by esafirm** [comment]
Closing this due inactivity. Please don't hesitate to reopen.
