### ISSUE TITLE
HomeAsUp Indicator color

### ISSUE THREAD

**Issue by tobias-r** [esafirm/android-image-picker#97]
It seems I cannot adjust the HomeAsUp indicator color of the picker.

It will always be white (which is not good, if you want a white background actionbar).

Any ideas on it?

**Comment by esafirm** [comment]
@tobias-r yeah currently you can't. Will add it on the next version

**Comment by esafirm** [comment]
@tobias-r i think this is suffice.

https://github.com/esafirm/android-image-picker/commit/943a1ce65788f321f2aae141a0e0f903a502993e

**Comment by tobias-r** [comment]
Hi! It works for me, although now I have a style in my styles.xml, in my colors.xml a color overwriting the text color and a programmatically set homeAsUp button color. Why don't you put it all in the styles.xml?

**Comment by esafirm** [comment]
@tobias-r currently the approach to change the arrow color is through `setColorFilter`. If we still want to use this approach and use a color in `style.xml` then every time `onCreate` triggered, we have to set the color filter with 

a. The default color in `style.xml` 
b. The designated color by user in config or user `style.xml`

My problem is that we have to set the color filter every time in `onCreate` when we actually don't need that. It just doesn't feel right. 

Do you have a better option than this?

**Comment by tobias-r** [comment]
In the ef_AppTheme you could add 
```
        <item name="android:textColorPrimary">@color/ef_colorTextPrimary</item>
        <item name="android:homeAsUpIndicator">@color/ef_colorTextPrimary</item>
        <item name="homeAsUpIndicator">@color/ef_colorTextPrimary</item>
```
and make it possible to overwrite these values same as "colorPrimary", etc.

Should work, no?

**Comment by esafirm** [comment]
And set the color filter (tint color) to arrow image every time?

**Comment by tobias-r** [comment]
If I assign a style to an activity with the 2 homeAsUpIndicator styles from above, it works for me without setting anything manually. But you are the master, if this is not working, leave it as it is.
