### ISSUE TITLE
New Glide causes a crash

### ISSUE THREAD

**Issue by absimas** [esafirm/android-image-picker#98]
In my project, if I use the latest `ImagePicker` (1.9.5) as well as the latest `Glide` (4.4.0) it causes a runtime crash of:
```java
java.lang.NoSuchMethodError: No virtual method into(Landroid/widget/ImageView;)Lcom/bumptech/glide/request/target/Target; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder' appears in /data/app/com.test/base.apk)
```

This is easily fixed by using the same glide version as does the `ImagePicker` - 4.3.1.

It would be useful, if this version requirement was documented.

**Comment by esafirm** [comment]
@absimas wow, i'm not aware of that. Will check on it

**Comment by esafirm** [comment]
@absimas [here](https://github.com/esafirm/android-image-picker/commit/d276a35014fa717c8ce50d0bc0306b67a770a689). Can't even compile the sample app using Glide 4.4.0+ so i just changed the tooling version to make it compilable, not sure if it's fix the problem.

I'm also add some note in [https://github.com/esafirm/android-image-picker/commit/77007377b040f71751e9c4bd62ec0b050eefdd9b]

**Comment by absimas** [comment]
@esafirm great! Works fine. Thank you.

**Comment by paveltech** [comment]
I also facing this issue but i solved this using latest version of glide

 implementation 'com.github.bumptech.glide:glide:4.9.0'
  annotationProcessor 'com.github.bumptech.glide:compiler:4.9.0'
